export type FamicomReferenceEntry = {
  productId: string
  publisher?: string
  releaseDate?: string
  alias?: string
}

export const famicomReferenceByGameId: Record<string, FamicomReferenceEntry> = {
  "famicom-%2789-dennou-kyusei-uranai": { productId: "IPC-J1", publisher: "Jingukan", releaseDate: "1988-10-12 00:00:00", alias: "'89 Dennou Kyuusei Uranai" },
  "famicom-10-yard-fight": { productId: "IF-02", publisher: "Irem", releaseDate: "08/30/1985" },
  "famicom-1942": { productId: "CAP-19, 01", publisher: "Capcom", releaseDate: "1985-11-12 00:00:00" },
  "famicom-4-nin-uchi-mahjong": { productId: "HVC-FJ", publisher: "Nintendo", releaseDate: "1984-02-11 00:00:00" },
  "famicom-8-eyes": { productId: "KKS-8E, 03", publisher: "Seta", releaseDate: "09/27/1988" },
  "famicom-a-ressha-de-ikou": { productId: "PHF-IX", publisher: "Pony Canyon", releaseDate: "08/21/1991" },
  "famicom-a-week-of-garfield": { productId: "TCC-VG", publisher: "Towa Chiki", releaseDate: "1989-07-04 00:00:00" },
  "famicom-abarenbou-tengu": { productId: "MDC-51", publisher: "Meldac", releaseDate: "12/14/1990" },
  "famicom-aces-iron-eagle-iii": { productId: "PAC-99", publisher: "Pack-In-Video", releaseDate: "1992-07-08 00:00:00" },
  "famicom-adventures-of-lolo": { productId: "HAL-A4", publisher: "HAL Laboratory", releaseDate: "1990-06-01 00:00:00" },
  "famicom-adventures-of-lolo-ii": { productId: "HAL-QL", publisher: "HAL Laboratory", releaseDate: "12/26/1990" },
  "famicom-after-burner": { productId: "SUN-AFB-6200", publisher: "Sunsoft", releaseDate: "03/30/1989" },
  "famicom-air-fortress": { productId: "HAL-AI", publisher: "HAL Laboratory", releaseDate: "08/17/1987" },
  "famicom-airwolf": { productId: "KYG-AX", publisher: "Kyugo", releaseDate: "12/24/1988" },
  "famicom-akira": { productId: "21", publisher: "Taito", releaseDate: "12/24/1988" },
  "famicom-akuma-no-shoutaijou": { productId: "KSC-UV", publisher: "Kemco / Icom Simulations", releaseDate: "09/29/1989" },
  "famicom-akumajou-densetsu": { productId: "RC845", publisher: "Konami / Konami", releaseDate: "12/22/1989" },
  "famicom-akumajou-dracula": { productId: "RV003", publisher: "Konami", releaseDate: "1993-05-02 00:00:00" },
  "famicom-alien-syndrome": { productId: "SAN-AZ", publisher: "Sunsoft", releaseDate: "1988-02-12 00:00:00" },
  "famicom-american-dream": { productId: "CDS-A7", publisher: "C-Dream", releaseDate: "09/23/1989" },
  "famicom-ankoku-shinwa-yamato-takeru-densetsu": { productId: "TKS-G6", publisher: "Tokyo Shoseki", releaseDate: "03/24/1989" },
  "famicom-aoki-ohkami-to-shiroki-mejika-genghis-khan": { productId: "KOE-GX", publisher: "Koei", releaseDate: "04/20/1989", alias: "Aoki Ookami to Shiroki Mejika: Genghis Khan" },
  "famicom-arabian-dream-scheherazade": { productId: "CBF-AS", publisher: "Culture Brain", releaseDate: "1987-03-09 00:00:00" },
  "famicom-argus": { productId: "JF-07", publisher: "Jaleco", releaseDate: "04/17/1986" },
  "famicom-arkanoid": { productId: "TFC-AN, 10", publisher: "Taito", releaseDate: "12/26/1986" },
  "famicom-arkanoid-ii": { productId: "TFC-ANII", publisher: "Taito", releaseDate: "1988-08-03 00:00:00" },
  "famicom-armadillo": { productId: "IGS-9T", publisher: "IGS", releaseDate: "1991-09-08 00:00:00" },
  "famicom-artelius": { productId: "NBF-AU", publisher: "Nichibutsu", releaseDate: "11/13/1987" },
  "famicom-asmik-kun-land": { productId: "ASM-YI", publisher: "Asmik", releaseDate: "12/20/1991" },
  "famicom-aso-armored-scrum-object": { productId: "SFX-AO", publisher: "SNK Electronics", releaseDate: "1986-03-09 00:00:00" },
  "famicom-astro-robo-sasa": { productId: "HSP-01", publisher: "ASCII / Mass Tael", releaseDate: "1985-09-08 00:00:00" },
  "famicom-athena": { productId: "SFX-AT", publisher: "SNK Electronics", releaseDate: "1987-05-06 00:00:00" },
  "famicom-atlantis-no-nazo": { productId: "SUN-ATL-4900", publisher: "Sunsoft", releaseDate: "04/17/1986" },
  "famicom-attack-animal-gakuen": { productId: "PNF-AA (R55V5913)", publisher: "Pony Canyon", releaseDate: "12/26/1987" },
  "famicom-b-wings": { productId: "DFC-BW", publisher: "Data East", releaseDate: "1986-03-06 00:00:00" },
  "famicom-babel-no-tou": { productId: "16", publisher: "Namco", releaseDate: "07/18/1986" },
  "famicom-bakushou-ai-no-gekijou": { productId: "CDS-IA", publisher: "Coconuts", releaseDate: "12/29/1990" },
  "famicom-bakushou-jinsei-gekijou": { productId: "TFC-BZG-5900-23", publisher: "Taito", releaseDate: "03/17/1989" },
  "famicom-bakushou-jinsei-gekijou-2": { productId: "TFC-BJ2, 35", publisher: "Taito", releaseDate: "03/22/1991" },
  "famicom-bakushou-jinsei-gekijou-3": { productId: "TFC-BJIII-6400-40", publisher: "Taito", releaseDate: "12/20/1991" },
  "famicom-bakushou-star-monomane-shitennou": { productId: "PAC-8M", publisher: "Pack-In-Video", releaseDate: "09/14/1990" },
  "famicom-ballblazer": { productId: "PNF-BZ", publisher: "Pony Canyon", releaseDate: "1988-04-03 00:00:00" },
  "famicom-balloon-fight": { productId: "HVC-BF", publisher: "Nintendo", releaseDate: "01/22/1985" },
  "famicom-baltron": { productId: "TDF-BT", publisher: "Toei Animation", releaseDate: "03/19/1986" },
  "famicom-banana": { productId: "VFR-B1", publisher: "Victor Musical", releaseDate: "1986-08-09 00:00:00" },
  "famicom-bananan-ouji-no-daibouken": { productId: "TFC-OJ", publisher: "Takara", releaseDate: "12/20/1991" },
  "famicom-barcode-world": { productId: "SUN-BBW-7200", publisher: "Sunsoft / Epoch", releaseDate: "12/18/1992" },
  "famicom-baseball": { productId: "HVC-BA", publisher: "Nintendo", releaseDate: "1983-07-12 00:00:00" },
  "famicom-baseball-fighter": { productId: "VAP-V9 (9509)", publisher: "Vap", releaseDate: "1991-05-07 00:00:00" },
  "famicom-batman": { productId: "SUN-BAT-6200", publisher: "Sunsoft", releaseDate: "12/22/1989" },
  "famicom-battle-baseball": { productId: "BAP-1Z", publisher: "Banpresto", releaseDate: "02/19/1993" },
  "famicom-battle-city": { productId: "NBC-4500, 09", publisher: "Namco", releaseDate: "1985-09-09 00:00:00" },
  "famicom-battle-fleet": { productId: "NAM-FBF-5900", publisher: "Namco", releaseDate: "06/22/1990" },
  "famicom-battle-formula": { productId: "TEC-5U", publisher: "Sunsoft / Tokai Engineering", releaseDate: "09/27/1991" },
  "famicom-battle-storm": { productId: "YZW-9Y", publisher: "Party Room 21", releaseDate: "12/21/1991" },
  "famicom-battletoads": { productId: "NCS-8T", publisher: "NCS / Masiya", releaseDate: "12/20/1991" },
  "famicom-best-keiba-derby-stallion": { productId: "HSP-46", publisher: "ASCII", releaseDate: "12/21/1991" },
  "famicom-binary-land": { productId: "HFC-BI", publisher: "Hudson Soft / Momo", releaseDate: "12/19/1985" },
  "famicom-bio-miracle-bokutte-upa": { productId: "RV102", publisher: "Konami", releaseDate: "02/26/1993" },
  "famicom-bird-week": { productId: "TFS-BK", publisher: "Toemiland / Toshiba EMI / Lenar", releaseDate: "1986-03-06 00:00:00" },
  "famicom-black-bass-ii": { productId: "GAM-BO", publisher: "Game Arts", releaseDate: "1987-06-02 00:00:00", alias: "Black Bass, The" },
  "famicom-blodia-land-puzzle-quest": { productId: "TKS-XF", publisher: "Tonkin House", releaseDate: "1990-11-08 00:00:00" },
  "famicom-blue-marlin": { productId: "GAM-8N", publisher: "Hot-B", releaseDate: "12/27/1991", alias: "Blue Marlin, The" },
  "famicom-bokosuka-wars": { productId: "HSP-04", publisher: "ASCII", releaseDate: "12/14/1985" },
  "famicom-bomber-king": { productId: "HFC-BX", publisher: "Hudson Soft", releaseDate: "1987-07-08 00:00:00" },
  "famicom-bomberman": { productId: "HFC-BM", publisher: "Hudson Soft / Momo", releaseDate: "12/19/1985" },
  "famicom-bomberman-ii": { productId: "HFC-2X", publisher: "Hudson Soft", releaseDate: "06/28/1991" },
  "famicom-booby-kids": { productId: "NBF-BB", publisher: "Nichibutsu", releaseDate: "1987-10-07 00:00:00" },
  "famicom-boulder-dash": { productId: "DFC-XB", publisher: "Data East", releaseDate: "03/23/1990" },
  "famicom-bubble-bobble-2": { productId: "TFC-BB", publisher: "Taito", releaseDate: "1993-05-03 00:00:00" },
  "famicom-bucky-o%27hare": { productId: "KDS-1V", publisher: "Konami", releaseDate: "01/31/1992" },
  "famicom-buggy-popper": { productId: "DFC-BP", publisher: "Data East", releaseDate: "1986-08-10 00:00:00" },
  "famicom-burai-fighter": { productId: "DTF-5F", publisher: "Taito / Taxan U.S.A.", releaseDate: "07/20/1990" },
  "famicom-burgertime": { productId: "11", publisher: "Namco", releaseDate: "11/27/1985" },
  "famicom-business-wars": { productId: "HCT-78 / 013", publisher: "Hect", releaseDate: "01/24/1992" },
  "famicom-cadillac": { productId: "HCT-C5", publisher: "Hect", releaseDate: "1990-02-02 00:00:00" },
  "famicom-capcom-barcelona-%2792": { productId: "CAP-1N", publisher: "Capcom", releaseDate: "1992-05-06 00:00:00" },
  "famicom-captain-ed": { productId: "CBS-ED", publisher: "CBS/Sony Group", releaseDate: "08/25/1989" },
  "famicom-captain-saver": { productId: "TFC-CS", publisher: "Taito", releaseDate: "09/29/1992" },
  "famicom-captain-silver": { productId: "GTS-CK", publisher: "Tokuma Soft / Data East", releaseDate: "12/16/1988" },
  "famicom-captain-tsubasa": { productId: "TCF-TP, 06", publisher: "Tecmo", releaseDate: "04/28/1988" },
  "famicom-casino-derby": { productId: "YZW-KD", publisher: "Party Room 21", releaseDate: "03/19/1993" },
  "famicom-castle-excellent": { productId: "HSP-05", publisher: "ASCII", releaseDate: "11/28/1986" },
  "famicom-castle-quest": { productId: "HFC-V4", publisher: "Hudson Soft", releaseDate: "05/18/1990" },
  "famicom-chack-%27n-pop": { productId: "2", publisher: "Taito", releaseDate: "05/24/1985" },
  "famicom-challenger": { productId: "HFC-CH", publisher: "Hudson Soft / Momo", releaseDate: "10/15/1985" },
  "famicom-championship-bowling": { productId: "ATH-8B", publisher: "Athena", releaseDate: "1991-08-02 00:00:00" },
  "famicom-championship-lode-runner": { productId: "HFC-CR", publisher: "Hudson Soft", releaseDate: "04/17/1985" },
  "famicom-chaos-world": { productId: "NAT-1W", publisher: "Natsume", releaseDate: "10/25/1991" },
  "famicom-chiyonofuji-no-ooichou": { productId: "FAC-EJ", publisher: "Face", releaseDate: "1990-07-12 00:00:00" },
  "famicom-choplifter": { productId: "JF-08", publisher: "Jaleco", releaseDate: "06/26/1986" },
  "famicom-choujikuu-yousai-macross": { productId: "NAM-NMR-4500", publisher: "Namco", releaseDate: "1985-10-12 00:00:00" },
  "famicom-choujin-sentai-jetman": { productId: "ANG-OY", publisher: "Angel", releaseDate: "12/21/1991" },
  "famicom-choujin-ultra-baseball": { productId: "CBF-UB", publisher: "Culture Brain", releaseDate: "10/27/1989" },
  "famicom-chuka-taisen": { productId: "DTF-CW, 27", publisher: "Taito", releaseDate: "09/22/1989" },
  "famicom-chuugoku-janshi-story-tonpuu": { productId: "NAT-T8", publisher: "Natsume", releaseDate: "12/23/1989" },
  "famicom-chuugoku-senseijutsu": { productId: "SAN-CQ", publisher: "Jaleco", releaseDate: "11/29/1988" },
  "famicom-circus-charlie": { productId: "SFC-CC", publisher: "Soft Pro International / Konami", releaseDate: "1986-04-03 00:00:00" },
  "famicom-city-connection": { productId: "JF-05", publisher: "Jaleco", releaseDate: "09/27/1985" },
  "famicom-clu-clu-land": { productId: "HVC-CL", publisher: "Nintendo", releaseDate: "11/22/1984" },
  "famicom-cobra-command": { productId: "DFC-CN", publisher: "Data East", releaseDate: "10/21/1988" },
  "famicom-cocoron": { productId: "TKR-8C", publisher: "Takeru", releaseDate: "1991-03-05 00:00:00" },
  "famicom-conflict": { productId: "VIC-C3", publisher: "Vic Tokai", releaseDate: "1989-01-12 00:00:00" },
  "famicom-contra": { productId: "RC826", publisher: "Konami / Konami", releaseDate: "1988-09-02 00:00:00" },
  "famicom-cosmic-epsilon": { productId: "ASM-EO", publisher: "Asmik", releaseDate: "11/24/1989" },
  "famicom-cosmic-wars": { productId: "KDS-CJ", publisher: "Konami", releaseDate: "1989-04-08 00:00:00" },
  "famicom-cosmo-genesis": { productId: "HSP-06", publisher: "ASCII", releaseDate: "12/23/1986" },
  "famicom-cosmo-police-galivan": { productId: "NBF-GV", publisher: "Nichibutsu", releaseDate: "1988-03-06 00:00:00" },
  "famicom-crazy-climber": { productId: "NBF-CY", publisher: "Nichibutsu", releaseDate: "12/26/1986" },
  "famicom-crisis-force": { productId: "RC856", publisher: "Konami", releaseDate: "08/27/1991" },
  "famicom-cross-fire": { productId: "KYG-C9", publisher: "Kyugo", releaseDate: "1990-02-11 00:00:00" },
  "famicom-dai-2-ji-super-robot-taisen": { productId: "BAP-N9", publisher: "Banpresto", releaseDate: "12/19/1991" },
  "famicom-daikoukai-jidai": { productId: "KOE-QK", publisher: "Koei", releaseDate: "03/15/1991" },
  "famicom-daiku-no-gen-san": { productId: "IF-24, TIX-59", publisher: "Irem", releaseDate: "11/15/1991" },
  "famicom-daisenryaku": { productId: "BTC-DY", publisher: "Bothtec", releaseDate: "1988-11-10 00:00:00" },
  "famicom-dark-lord": { productId: "DFC-25", publisher: "Data East", releaseDate: "1991-08-02 00:00:00" },
  "famicom-dash-yarou": { productId: "VIS-5D", publisher: "Visco", releaseDate: "06/15/1990" },
  "famicom-datsugoku": { productId: "KAC-P7", publisher: "K. Amusement", releaseDate: "06/30/1989" },
  "famicom-de-block": { productId: "ATH-9L", publisher: "Athena", releaseDate: "1991-09-08 00:00:00" },
  "famicom-dead-fox": { productId: "CAP-VP", publisher: "Capcom", releaseDate: "02/23/1990" },
  "famicom-dengeki-big-bang": { productId: "VIC-B6", publisher: "Vic Tokai", releaseDate: "01/27/1989" },
  "famicom-devil-man": { productId: "NAM-DM-5500", publisher: "Namco", releaseDate: "04/25/1989" },
  "famicom-devil-world": { productId: "HVC-DD", publisher: "Nintendo", releaseDate: "1984-05-10 00:00:00" },
  "famicom-die-hard": { productId: "PAC-57", publisher: "Pack-In-Video", releaseDate: "07/19/1991" },
  "famicom-dig-dug": { productId: "NDD-4500, 06", publisher: "Namco", releaseDate: "1985-04-06 00:00:00" },
  "famicom-dig-dug-ii": { productId: "14", publisher: "Namco", releaseDate: "04/18/1986" },
  "famicom-dokuganryu-masamune": { productId: "NAM-DG-5500", publisher: "Namco", releaseDate: "1988-05-04 00:00:00", alias: "Dokuganryuu Masamune" },
  "famicom-don-doko-don": { productId: "TFC-DD", publisher: "Taito", releaseDate: "1990-09-03 00:00:00" },
  "famicom-don-doko-don-2": { productId: "41", publisher: "Taito", releaseDate: "01/31/1992" },
  "famicom-donald-duck": { productId: "KSC-WS", publisher: "Kemco / Kemco", releaseDate: "09/22/1988" },
  "famicom-donald-land": { productId: "DFC-DX", publisher: "Data East", releaseDate: "01/29/1988" },
  "famicom-donkey-kong": { productId: "HVC-DK", publisher: "Nintendo", releaseDate: "07/15/1983" },
  "famicom-donkey-kong-3": { productId: "HVC-DT", publisher: "Nintendo", releaseDate: "1984-04-07 00:00:00" },
  "famicom-donkey-kong-jr": { productId: "HVC-JR", publisher: "Nintendo", releaseDate: "07/15/1983" },
  "famicom-donkey-kong-jr-no-sansuu-asobi": { productId: "HVC-CA", publisher: "Nintendo", releaseDate: "1983-12-12 00:00:00" },
  "famicom-door-door": { productId: "EFC-DR", publisher: "Enix", releaseDate: "07/18/1985" },
  "famicom-doraemon": { productId: "HFC-DO", publisher: "Hudson Soft", releaseDate: "1986-12-12 00:00:00" },
  "famicom-double-dragon": { productId: "TJC-WD", publisher: "Technos Japan", releaseDate: "1988-08-04 00:00:00" },
  "famicom-double-moon-densetsu": { productId: "NCS-1T", publisher: "NCS / Masiya", releaseDate: "10/30/1992" },
  "famicom-dough-boy": { productId: "KSC-DB", publisher: "Kemco / Synapse", releaseDate: "1985-11-12 00:00:00" },
  "famicom-downtown-nekketsu-monogatari": { productId: "TJC-DN", publisher: "Technos Japan", releaseDate: "04/25/1989" },
  "famicom-dr-mario": { productId: "HVC-VU", publisher: "Nintendo", releaseDate: "07/27/1990" },
  "famicom-dragon%27s-lair": { productId: "ESF-IP", publisher: "Epic/Sony Records", releaseDate: "09/20/1991" },
  "famicom-dragon-ball-3-gokuu-den": { productId: "BA-DB3", publisher: "Bandai", releaseDate: "10/27/1989" },
  "famicom-dragon-ball-dai-maou-fukkatsu": { productId: "BA-DB2", publisher: "Bandai", releaseDate: "1988-12-08 00:00:00" },
  "famicom-dragon-ball-shen-long-no-nazo": { productId: "BA-DRA", publisher: "Bandai", releaseDate: "11/27/1986" },
  "famicom-dragon-ball-z-kyoushuu-saiyajin": { productId: "BA-DBZ", publisher: "Bandai", releaseDate: "10/27/1990" },
  "famicom-dragon-buster": { productId: "NAM-DB-4900", publisher: "Namco", releaseDate: "1987-07-01 00:00:00" },
  "famicom-dragon-fighter": { productId: "TCC-1D", publisher: "Towa Chiki", releaseDate: "1990-10-08 00:00:00" },
  "famicom-dragon-ninja": { productId: "NAM-DN-5800", publisher: "Namco", releaseDate: "07/14/1989" },
  "famicom-dragon-quest": { productId: "EFC-DQ", publisher: "Enix", releaseDate: "05/27/1986" },
  "famicom-dragon-scroll-yomigaerishi-maryuu": { productId: "KON-RC823", publisher: "Konami", releaseDate: "1987-04-12 00:00:00" },
  "famicom-dragon-unit": { productId: "ATH-ZX", publisher: "Athena", releaseDate: "02/27/1990" },
  "famicom-dragon-wars": { productId: "KSC-Z9", publisher: "Kemco", releaseDate: "1991-09-08 00:00:00" },
  "famicom-dream-master": { productId: "NAM-FPZ-5800", publisher: "Namco / Prism Zone", releaseDate: "09/22/1992" },
  "famicom-duck-hunt": { productId: "HVC-DH", publisher: "Nintendo", releaseDate: "04/21/1984" },
  "famicom-duck-tales-2": { productId: "CAP-DW", publisher: "Capcom", releaseDate: "04/23/1993" },
  "famicom-dungeon-kid": { productId: "BTC-7D", publisher: "Quest", releaseDate: "08/31/1990" },
  "famicom-dynamite-batman": { productId: "SUN-DBT-6500", publisher: "Sunsoft", releaseDate: "12/20/1991" },
  "famicom-dynamite-bowl": { productId: "TFS-DL", publisher: "Toemiland", releaseDate: "05/24/1987" },
  "famicom-egypt": { productId: "HUM-E9", publisher: "Human / Human Creative", releaseDate: "05/31/1991" },
  "famicom-elevator-action": { productId: "TF-4900, 04", publisher: "Taito", releaseDate: "06/28/1985" },
  "famicom-elysion": { productId: "TKS-G4", publisher: "Tokyo Shoseki", releaseDate: "04/28/1988" },
  "famicom-emo-yan-no-10-bai-pro-yakyuu": { productId: "HCT-IB", publisher: "Hect", releaseDate: "12/19/1989" },
  "famicom-erika-to-satoru-no-yume-bouken": { productId: "NAM-YB-4900", publisher: "Namco", releaseDate: "09/27/1988" },
  "famicom-erunaaku-no-zaihou": { productId: "TCC-EL", publisher: "Towa Chiki", releaseDate: "1987-10-08 00:00:00" },
  "famicom-esper-boukentai": { productId: "JF-15", publisher: "Jaleco", releaseDate: "10/13/1987", alias: "Esper Bouken Tai" },
  "famicom-excitebike": { productId: "HVC-EB", publisher: "Nintendo", releaseDate: "11/30/1984" },
  "famicom-exciting-boxing": { productId: "RC250", publisher: "Konami", releaseDate: "12/16/1987" },
  "famicom-exciting-rally": { productId: "VRE-E2", publisher: "Kaken", releaseDate: "04/24/1992" },
  "famicom-exed-exes": { productId: "GTS-EE", publisher: "Tokuma Shoten / Capcom", releaseDate: "11/21/1985" },
  "famicom-exerion": { productId: "JF-01", publisher: "Jaleco", releaseDate: "1985-11-02 00:00:00" },
  "famicom-f1-circus": { productId: "NBF-7F", publisher: "Nichibutsu", releaseDate: "1992-07-02 00:00:00" },
  "famicom-f1-race": { productId: "HVC-FR", publisher: "Nintendo", releaseDate: "1984-02-11 00:00:00" },
  "famicom-f1-sensation": { productId: "KDS-FE", publisher: "Konami", releaseDate: "01/29/1993", alias: "F-1 Sensation" },
  "famicom-famicom-shogi-ryuousen": { productId: "IMX-1R", publisher: "I'Max", releaseDate: "02/15/1991" },
  "famicom-famicom-wars": { productId: "HVC-FW", publisher: "Nintendo / Intelligent Systems", releaseDate: "1988-12-08 00:00:00" },
  "famicom-famicom-yakyuu-ban": { productId: "EPO-EY", publisher: "Epoch", releaseDate: "12/15/1989" },
  "famicom-family-basic": { productId: "HVC-BS", publisher: "Nintendo", releaseDate: "06/21/1984" },
  "famicom-family-basic-v3": { productId: "HVC-VT", publisher: "Nintendo / Sharp", releaseDate: "02/21/1985", alias: "Family BASIC v3.0" },
  "famicom-family-block": { productId: "ATH-4T", publisher: "Athena", releaseDate: "1991-12-04 00:00:00" },
  "famicom-family-boxing": { productId: "NAM-FB-4900", publisher: "Namco", releaseDate: "06/19/1987" },
  "famicom-family-circuit": { productId: "NAM-FC-3900", publisher: "Namco", releaseDate: "1988-06-01 00:00:00" },
  "famicom-family-circuit-%2791": { productId: "NAM-FC91-7800", publisher: "Namco", releaseDate: "07/19/1991" },
  "famicom-family-jockey": { productId: "NAM-FJ-3900", publisher: "Namco", releaseDate: "04/24/1987" },
  "famicom-family-mahjong": { productId: "NAM-FM-3900", publisher: "Namco", releaseDate: "1987-11-08 00:00:00" },
  "famicom-family-pinball": { productId: "NAM-FP-4900", publisher: "Namco / Artman", releaseDate: "03/24/1989" },
  "famicom-family-tennis": { productId: "NAM-FT-3900", publisher: "Namco", releaseDate: "1987-11-12 00:00:00" },
  "famicom-famista-%2790": { productId: "NAM-F90-5800", publisher: "Namco", releaseDate: "12/19/1989" },
  "famicom-famista-%2791": { productId: "NAM-F91-4900", publisher: "Namco", releaseDate: "12/21/1990" },
  "famicom-famista-%2792": { productId: "NAM-F92-5000", publisher: "Namco", releaseDate: "12/20/1991" },
  "famicom-famista-%2793": { productId: "NAM-F93-4900", publisher: "Namco", releaseDate: "12/22/1992" },
  "famicom-famista-%2794": { productId: "NAM-F94-3900", publisher: "Namco", releaseDate: "1993-01-12 00:00:00" },
  "famicom-fantasy-zone": { productId: "SUN-FZ-5300", publisher: "Sunsoft", releaseDate: "07/20/1987" },
  "famicom-faxanadu": { productId: "HFC-FX", publisher: "Hudson Soft", releaseDate: "11/16/1987" },
  "famicom-ferrari-grand-prix-challenge": { productId: "CDS-FS", publisher: "Coconuts / C-Dream", releaseDate: "11/13/1992" },
  "famicom-field-combat": { productId: "JF-04", publisher: "Jaleco", releaseDate: "1985-09-07 00:00:00" },
  "famicom-fighting-golf": { productId: "SFX-FI", publisher: "SNK Electronics", releaseDate: "03/24/1988" },
  "famicom-fighting-road": { productId: "TDF-FG", publisher: "Toei Animation", releaseDate: "12/13/1988" },
  "famicom-final-fantasy": { productId: "SQF-FF", publisher: "Square Soft", releaseDate: "12/18/1987" },
  "famicom-final-fantasy-i-&amp;-ii": { productId: "SQF-FO", publisher: "Square Soft", releaseDate: "02/27/1994" },
  "famicom-final-fantasy-ii": { productId: "SQF-FY", publisher: "Square Soft", releaseDate: "12/17/1988" },
  "famicom-final-fantasy-iii": { productId: "SQF-FC", publisher: "Square Soft", releaseDate: "04/27/1990" },
  "famicom-final-lap": { productId: "NAM-FL-5200", publisher: "Namco", releaseDate: "1988-12-08 00:00:00" },
  "famicom-final-mission": { productId: "NAT-FV", publisher: "Natsume", releaseDate: "06/22/1990" },
  "famicom-fire-emblem-ankoku-ryu-to-hikari-no-tsurugi": { productId: "HVC-VX", publisher: "Nintendo", releaseDate: "04/20/1990", alias: "Fire Emblem: Ankokuryuu to Hikari no Ken" },
  "famicom-fire-emblem-gaiden": { productId: "HVC-2I", publisher: "Nintendo", releaseDate: "03/14/1992" },
  "famicom-flappy": { productId: "dBF-FL", publisher: "dB-Soft", releaseDate: "06/14/1985" },
  "famicom-fleet-commander": { productId: "HSP-10", publisher: "ASCII", releaseDate: "03/29/1988" },
  "famicom-flintstones-the-rescue-of-dino-&amp;-hoppy": { productId: "TFC-FS", publisher: "Taito", releaseDate: "1992-07-08 00:00:00", alias: "Flintstones: The Rescue of Dino & Hoppy, The" },
  "famicom-flying-hero": { productId: "ESF-FZ/55.6R-3", publisher: "CBS/Sony Group / Aicom", releaseDate: "02/17/1989" },
  "famicom-formation-z": { productId: "JF-02", publisher: "Jaleco", releaseDate: "1985-04-04 00:00:00" },
  "famicom-front-line": { productId: "3", publisher: "Taito", releaseDate: "1985-01-08 00:00:00" },
  "famicom-fudou-myououden": { productId: "TFC-FM, 17", publisher: "Taito", releaseDate: "03/29/1988", alias: "Fudou Myouou Den" },
  "famicom-fushigi-no-umi-no-nadia": { productId: "THF-FD", publisher: "Toho", releaseDate: "03/15/1991" },
  "famicom-fuzzical-fighter": { productId: "SEI-1E", publisher: "Sigma", releaseDate: "05/17/1991" },
  "famicom-galaga": { productId: "NGG-4500, 05", publisher: "Namco", releaseDate: "02/15/1985" },
  "famicom-galaxian": { productId: "NGX-4500, 01", publisher: "Namco / Namco", releaseDate: "1984-07-09 00:00:00" },
  "famicom-gambler-jiko-chuushinha": { productId: "ASM-GJ", publisher: "Asmik", releaseDate: "1988-11-11 00:00:00" },
  "famicom-gambler-jiko-chuushinha-2": { productId: "ASM-2J", publisher: "Asmik", releaseDate: "1990-07-12 00:00:00" },
  "famicom-game-party": { productId: "CDS-P8", publisher: "Coconuts / C-Dream", releaseDate: "07/27/1990" },
  "famicom-ganbare-goemon-2": { productId: "RC833", publisher: "Konami", releaseDate: "1989-04-01 00:00:00" },
  "famicom-ganbare-goemon-karakuri-douchuu": { productId: "RC815", publisher: "Konami", releaseDate: "07/30/1986" },
  "famicom-ganbare-pennant-race": { productId: "RC834", publisher: "Konami", releaseDate: "02/28/1989" },
  "famicom-ganso-saiyuuki-super-monkey-daibouken": { productId: "VAP-GS", publisher: "Vap", releaseDate: "11/21/1986" },
  "famicom-geimos": { productId: "HSP-02", publisher: "ASCII / Wixel", releaseDate: "08/28/1985" },
  "famicom-gekikame-ninja-den": { productId: "KDS-GN", publisher: "Konami", releaseDate: "1989-12-05 00:00:00" },
  "famicom-gekitotsu-yonku-battle": { productId: "IF-15", publisher: "Irem / Irem", releaseDate: "11/17/1989" },
  "famicom-gekitou-pro-wrestling-toukon-densetsu": { productId: "TCF-PZ", publisher: "Tecmo", releaseDate: "1989-01-09 00:00:00", alias: "Gekitou Puroresu!! Toukon Densetsu" },
  "famicom-gekitou-stadium": { productId: "TCF-EF, 09", publisher: "Tecmo", releaseDate: "12/15/1989" },
  "famicom-getsufuu-maden": { productId: "RC819", publisher: "Konami", releaseDate: "1987-07-07 00:00:00" },
  "famicom-ghostbusters": { productId: "GTS-GB", publisher: "Tokuma Soft", releaseDate: "09/22/1986" },
  "famicom-gimmick": { productId: "SUN-GMK-6200", publisher: "Sunsoft", releaseDate: "01/31/1992" },
  "famicom-ginga-eiyuu-densetsu": { productId: "KSC-GE", publisher: "Kemco", releaseDate: "12/21/1988" },
  "famicom-ginga-no-sannin": { productId: "HVC-GT", publisher: "Nintendo", releaseDate: "12/15/1987" },
  "famicom-godzilla": { productId: "THF-GZ", publisher: "Toho", releaseDate: "1988-09-12 00:00:00" },
  "famicom-golf": { productId: "HVC-GF", publisher: "Nintendo", releaseDate: "1984-01-05 00:00:00" },
  "famicom-golf-club-birdie-rush": { productId: "DFC-GH", publisher: "Data East", releaseDate: "1987-09-12 00:00:00" },
  "famicom-golf-grand-slam": { productId: "HCT-7G", publisher: "Hect", releaseDate: "01/31/1991" },
  "famicom-golf-ko-open": { productId: "TFC-GO, 26", publisher: "Taito", releaseDate: "11/25/1989" },
  "famicom-gorby-no-pipeline-daisakusen": { productId: "GTS-4G", publisher: "Tokuma Soft", releaseDate: "1991-12-04 00:00:00" },
  "famicom-gorilla-man": { productId: "YZW-GR", publisher: "Party Room 21 / Party Tap", releaseDate: "04/28/1993", alias: "Gorilla Man, The" },
  "famicom-gradius": { productId: "RC810", publisher: "Konami", releaseDate: "04/25/1986" },
  "famicom-gradius-ii": { productId: "RC832", publisher: "Konami / Konami", releaseDate: "12/16/1988" },
  "famicom-grand-master": { productId: "VRE-IE", publisher: "Varie", releaseDate: "02/26/1991" },
  "famicom-great-battle-cyber": { productId: "BAP-GC", publisher: "Banpresto", releaseDate: "12/25/1992" },
  "famicom-great-deal": { productId: "HCT-79", publisher: "Hect", releaseDate: "10/25/1991" },
  "famicom-great-tank": { productId: "SFX-TV", publisher: "SNK Electronics", releaseDate: "07/29/1988" },
  "famicom-guardic-gaiden": { productId: "IF-08", publisher: "Irem", releaseDate: "1987-05-02 00:00:00" },
  "famicom-guevara": { productId: "SFX-GQ", publisher: "SNK Electronics", releaseDate: "12/26/1988" },
  "famicom-gun-dec": { productId: "SAC-9G", publisher: "Sammy", releaseDate: "04/26/1991" },
  "famicom-gun-nac": { productId: "TKS-XG", publisher: "Tonkin House", releaseDate: "1990-05-10 00:00:00" },
  "famicom-gun-sight": { productId: "KDS-8G", publisher: "Konami", releaseDate: "03/15/1991", alias: "Gunsight" },
  "famicom-gyrodine": { productId: "TFC-GD, 06", publisher: "Taito", releaseDate: "03/13/1986" },
  "famicom-haja-no-fuuin": { productId: "HSP-08", publisher: "ASCII", releaseDate: "10/23/1987" },
  "famicom-hana-no-star-kaidou": { productId: "VFR-H1-02", publisher: "Victor Musical", releaseDate: "03/17/1987" },
  "famicom-hanjuku-hero": { productId: "SQF-HJ", publisher: "Square Soft", releaseDate: "1988-02-12 00:00:00" },
  "famicom-happy-birthday-bugs": { productId: "KSC-H8", publisher: "Kemco", releaseDate: "1990-03-08 00:00:00" },
  "famicom-hatris": { productId: "BPS-JZ", publisher: "Bullet-Proof Software", releaseDate: "1990-06-07 00:00:00" },
  "famicom-hayauchi-super-igo": { productId: "NAM-X79-5900", publisher: "Namco", releaseDate: "1989-03-03 00:00:00" },
  "famicom-heavy-barrel": { productId: "DFC-XH", publisher: "Data East", releaseDate: "1990-02-03 00:00:00" },
  "famicom-hebereke": { productId: "SUN-HEB-6200", publisher: "Sunsoft", releaseDate: "09/20/1991" },
  "famicom-hector-%2787": { productId: "HFC-HH", publisher: "Hudson Soft", releaseDate: "07/16/1987" },
  "famicom-heisei-tensai-bakabon": { productId: "NAM-FTB-5800", publisher: "Namco", releaseDate: "1991-06-12 00:00:00" },
  "famicom-hello-kitty-no-hanabatake": { productId: "CTS-HL", publisher: "Character Soft", releaseDate: "1992-11-12 00:00:00", alias: "Hello Kitty no Ohanabatake" },
  "famicom-hello-kitty-world": { productId: "CTS-HW", publisher: "Character Soft", releaseDate: "03/27/1992" },
  "famicom-highway-star": { productId: "SQF-HI", publisher: "Square Soft", releaseDate: "1987-07-08 00:00:00" },
  "famicom-hirake-ponkikki": { productId: "TFC-PK", publisher: "Takara", releaseDate: "04/17/1992" },
  "famicom-hiryuu-no-ken-ougi-no-sho": { productId: "NFC-HR", publisher: "Culture Brain", releaseDate: "02/14/1987" },
  "famicom-hiryuu-no-ken-special-fighting-wars": { productId: "CBF-4N", publisher: "Culture Brain", releaseDate: "06/21/1991" },
  "famicom-hissatsu-doujou-yaburi": { productId: "SEI-1A", publisher: "Sigma", releaseDate: "07/18/1989" },
  "famicom-hissatsu-shigotonin": { productId: "BAP-X7", publisher: "Banpresto", releaseDate: "12/15/1990", alias: "Hissatsu Shigoto Nin" },
  "famicom-hogan%27s-alley": { productId: "HVC-HA", publisher: "Nintendo", releaseDate: "1984-12-06 00:00:00" },
  "famicom-hokuto-no-ken": { productId: "TDF-HK", publisher: "Toei Animation", releaseDate: "1986-10-08 00:00:00" },
  "famicom-holy-diver": { productId: "IF-12", publisher: "Irem", releaseDate: "04/28/1989" },
  "famicom-home-run-nighter-pennant-league": { productId: "DFC-YQ", publisher: "Data East", releaseDate: "03/31/1989" },
  "famicom-hook": { productId: "ESF-7Q / ESPG43", publisher: "Epic/Sony Records", releaseDate: "03/27/1992" },
  "famicom-hoshi-wo-miru-hito": { productId: "GAM-HM-02", publisher: "Hot-B / Game Arts", releaseDate: "10/27/1987", alias: "Hoshi o Miru Hito" },
  "famicom-hototogisu": { productId: "IF-10, TIX-Z1", publisher: "Irem", releaseDate: "08/19/1988" },
  "famicom-hudson-hawk": { productId: "ESF-Y4 / ESPG40", publisher: "Epic/Sony Records", releaseDate: "12/27/1991" },
  "famicom-hyakki-yagyou": { productId: "USE-HG", publisher: "Use", releaseDate: "02/23/1989" },
  "famicom-hyaku-no-sekai-no-monogatari": { productId: "ASK-71", publisher: "ASK", releaseDate: "1991-09-08 00:00:00" },
  "famicom-hydlide-special": { productId: "TFS-HS", publisher: "Toemiland / Toshiba EMI", releaseDate: "03/18/1986" },
  "famicom-hyper-olympic": { productId: "RC800", publisher: "Konami", releaseDate: "06/21/1985" },
  "famicom-hyper-sports": { productId: "KON-RC806", publisher: "Konami", releaseDate: "09/27/1985" },
  "famicom-i-love-softball": { productId: "CDS-S6", publisher: "C-Dream", releaseDate: "12/19/1989" },
  "famicom-ice-climber": { productId: "HVC-IC", publisher: "Nintendo", releaseDate: "01/30/1985" },
  "famicom-ide-yousuke-meijin-no-jissen-mahjong": { productId: "CAP-IM", publisher: "Capcom", releaseDate: "09/24/1987" },
  "famicom-ide-yousuke-meijin-no-jissen-mahjong-ii": { productId: "CAP-2Q", publisher: "Capcom", releaseDate: "02/22/1991" },
  "famicom-idol-hakkenden": { productId: "TCC-I8", publisher: "Towa Chiki", releaseDate: "09/14/1989" },
  "famicom-igo-kuroban-taikyoku": { productId: "BPS-IG", publisher: "Bullet-Proof Software", releaseDate: "1987-11-08 00:00:00", alias: "Igo: Kyuroban Taikyoku" },
  "famicom-igo-meikan": { productId: "HCT-II / 006", publisher: "Hect", releaseDate: "1990-10-01 00:00:00" },
  "famicom-igo-shinan": { productId: "HCT-ID", publisher: "Hect", releaseDate: "07/14/1989" },
  "famicom-igo-shinan-%2791": { productId: "HCT-9A", publisher: "Hect", releaseDate: "1991-05-07 00:00:00" },
  "famicom-igo-shinan-%2792": { productId: "HCT-53", publisher: "Hect", releaseDate: "1992-10-03 00:00:00" },
  "famicom-igo-shinan-%2793": { productId: "HCT-IF / 018", publisher: "Hect", releaseDate: "11/27/1992" },
  "famicom-igo-shinan-%2794": { productId: "HCT-IR", publisher: "Hect", releaseDate: "12/17/1993" },
  "famicom-ikari": { productId: "KAC-IK", publisher: "K. Amusement / SNK Electronics", releaseDate: "11/26/1986" },
  "famicom-ikinari-musician": { productId: "TKS-G1", publisher: "Tokyo Shoseki", releaseDate: "1987-05-03 00:00:00" },
  "famicom-ikki": { productId: "SUN-RIK-4900", publisher: "Sunsoft", releaseDate: "11/28/1985" },
  "famicom-image-fight": { productId: "IF-14", publisher: "Irem", releaseDate: "03/16/1990" },
  "famicom-indora-no-hikari": { productId: "KSC-IN", publisher: "Kemco", releaseDate: "10/20/1987" },
  "famicom-insector-x": { productId: "TFC-IS", publisher: "Taito", releaseDate: "09/21/1990" },
  "famicom-isaki-shuugorou-no-keiba-hisshou-gaku": { productId: "IMA-EK", publisher: "Imagineer", releaseDate: "03/30/1990" },
  "famicom-ishin-no-arashi": { productId: "KOE-XK", publisher: "Koei", releaseDate: "09/15/1990" },
  "famicom-j-league-winning-goal": { productId: "HVC-W3", publisher: "Electronic Arts", releaseDate: "05/27/1994" },
  "famicom-jackie-chan": { productId: "HFC-V5", publisher: "Hudson Soft", releaseDate: "01/25/1991" },
  "famicom-jajamaru-ninpouchou": { productId: "JF-22", publisher: "Jaleco", releaseDate: "03/28/1989" },
  "famicom-jajamaru-no-daibouken": { productId: "JF-09", publisher: "Jaleco", releaseDate: "08/22/1986" },
  "famicom-jangou": { productId: "VFR-Q3-10", publisher: "Victor Musical", releaseDate: "08/30/1990" },
  "famicom-jetsons-cogswell%27s-caper": { productId: "TFC-JS", publisher: "Taito", releaseDate: "04/23/1993", alias: "Jetsons: Cogswell's Caper, The" },
  "famicom-jigoku-gokuraku-maru": { productId: "PAC-9Z", publisher: "Pack-In-Video", releaseDate: "12/21/1990" },
  "famicom-jongbou": { productId: "KAC-JB", publisher: "K. Amusement", releaseDate: "07/18/1987" },
  "famicom-joust": { productId: "HAL-JU", publisher: "HAL Laboratories / HAL Laboratories", releaseDate: "10/30/1987" },
  "famicom-joy-mech-fight": { productId: "HVC-JM", publisher: "Nintendo", releaseDate: "05/21/1993" },
  "famicom-juju-densetsu": { productId: "DTF-5J", publisher: "Taito", releaseDate: "07/19/1991" },
  "famicom-jumbo-ozaki-no-hole-in-one-professional": { productId: "HAL-JO", publisher: "HAL Laboratories", releaseDate: "1988-01-02 00:00:00" },
  "famicom-just-breed": { productId: "EFC-I5", publisher: "Enix", releaseDate: "12/15/1992" },
  "famicom-juvei-quest": { productId: "NAM-FJQ-7800", publisher: "Namco", releaseDate: "1991-04-01 00:00:00" },
  "famicom-kagerou-densetsu": { productId: "PIX-XA-01", publisher: "Pixel", releaseDate: "1990-11-05 00:00:00" },
  "famicom-kaguya-hime-densetsu": { productId: "VFR-K1-06", publisher: "Victor Musical", releaseDate: "12/16/1988" },
  "famicom-kaijuu-monogatari": { productId: "NAM-KM-5500", publisher: "Namco / Birthday", releaseDate: "11/18/1988" },
  "famicom-kaiketsu-yanchamaru": { productId: "IF-07", publisher: "Irem", releaseDate: "1987-02-10 00:00:00" },
  "famicom-kamen-no-ninja-akakage": { productId: "TDF-AK", publisher: "Toei Animation / Shouei System", releaseDate: "05/20/1988" },
  "famicom-kamen-no-ninja-hanamaru": { productId: "CAP-JE", publisher: "Capcom", releaseDate: "03/16/1990" },
  "famicom-kanshakudama-nage-kantarou-no-toukaidou-gojuusan-tsugi": { productId: "SUN-TKR-4900", publisher: "Sunsoft", releaseDate: "1986-03-07 00:00:00" },
  "famicom-karateka": { productId: "SFC-KR", publisher: "Soft Pro International / Broderbund", releaseDate: "1985-05-12 00:00:00" },
  "famicom-karnov": { productId: "NAM-KA-4900", publisher: "Namco / Data East", releaseDate: "12/18/1987" },
  "famicom-kawa-no-nushi-tsuri": { productId: "PAC-7K", publisher: "Pack-In-Video", releaseDate: "1990-10-08 00:00:00" },
  "famicom-kero-kero-keroppi-no-daibouken": { productId: "CTS-ZI", publisher: "Sanrio / Character Soft", releaseDate: "03/29/1991" },
  "famicom-keroppi-to-keroriinu-no-splash-bomb": { productId: "CTS-SY", publisher: "Sanrio / Character Soft", releaseDate: "1993-01-12 00:00:00" },
  "famicom-king%27s-knight": { productId: "SQF-KG", publisher: "Square Soft / Workss", releaseDate: "09/18/1986" },
  "famicom-king-of-kings": { productId: "NAM-KK-5900", publisher: "Namco", releaseDate: "1988-09-12 00:00:00" },
  "famicom-kiteretsu-daihyakka": { productId: "EPO-KT", publisher: "Epoch", releaseDate: "02/23/1990" },
  "famicom-klax": { productId: "HFC-V6", publisher: "Hudson Soft / Atari", releaseDate: "12/14/1990" },
  "famicom-knight-rider": { productId: "PAC-NR", publisher: "Pack-In-Video", releaseDate: "09/30/1988" },
  "famicom-konami-wai-wai-world": { productId: "RC825", publisher: "Konami", releaseDate: "01/14/1988" },
  "famicom-konamic-sports-in-seoul": { productId: "KDS-F2", publisher: "Konami", releaseDate: "09/16/1989" },
  "famicom-koushien": { productId: "KAC-KQ", publisher: "K. Amusement", releaseDate: "1989-06-10 00:00:00" },
  "famicom-kujaku-ou": { productId: "PNF-KZ (R58V5916)", publisher: "Pony Canyon", releaseDate: "09/21/1988" },
  "famicom-kujaku-ou-ii": { productId: "PNF-QW", publisher: "Pony Canyon", releaseDate: "08/21/1990" },
  "famicom-kunio-kun-no-nekketsu-soccer-league": { productId: "TJC-NV", publisher: "Technos Japan", releaseDate: "04/23/1993" },
  "famicom-kurogane-hiroshi-no-yosou-daisuki-kachiuma-densetsu": { productId: "NBF-R7", publisher: "Nichibutsu", releaseDate: "04/20/1990" },
  "famicom-kyorochan-land": { productId: "HR-4C", publisher: "Hiro / Triffix", releaseDate: "1992-11-12 00:00:00" },
  "famicom-kyukyoku-harikiri-koushien": { productId: "TFC-KHK-6900-42", publisher: "Taito", releaseDate: "03/19/1992", alias: "Kyuukyoku Harikiri Koushien" },
  "famicom-kyukyoku-harikiri-stadium-heisei-gannen-ban": { productId: "TFC-KHH-6800-25", publisher: "Taito", releaseDate: "07/21/1989", alias: "Kyuukyoku Harikiri Stadium: Heisei Gannen Ban" },
  "famicom-kyuukyoku-harikiri-stadium": { productId: "TFC-KHS-5500-18", publisher: "Taito", releaseDate: "06/28/1988" },
  "famicom-kyuukyoku-harikiri-stadium-iii": { productId: "TFC-KH", publisher: "Taito", releaseDate: "1991-01-03 00:00:00" },
  "famicom-kyuukyoku-tiger": { productId: "CBS-QT", publisher: "CBS/Sony / Taito", releaseDate: "1989-04-08 00:00:00" },
  "famicom-l%27empereur": { productId: "KOE-QV", publisher: "Koei", releaseDate: "05/23/1991" },
  "famicom-labyrinth": { productId: "GTS-LA", publisher: "Tokuma Soft", releaseDate: "1987-07-01 00:00:00" },
  "famicom-lagrange-point": { productId: "KON-RC851", publisher: "Konami", releaseDate: "04/26/1991" },
  "famicom-last-armageddon": { productId: "SHI-LT", publisher: "Yutaka / Braingrey-Mind", releaseDate: "1990-10-11 00:00:00" },
  "famicom-law-of-the-west": { productId: "PNF-LW (R53V5907)", publisher: "Pony Canyon / Accolade", releaseDate: "1987-06-03 00:00:00" },
  "famicom-layla": { productId: "dBF-LY", publisher: "dB-Soft", releaseDate: "12/20/1986" },
  "famicom-legend-of-kage": { productId: "TFC-KD, 07", publisher: "Taito", releaseDate: "04/18/1986", alias: "Legend of Kage, The" },
  "famicom-little-magic": { productId: "DFC-LG", publisher: "Data East", releaseDate: "09/14/1990" },
  "famicom-lode-runner": { productId: "HFC-LR", publisher: "Hudson Soft / Broderbund", releaseDate: "07/31/1984" },
  "famicom-lord-of-king": { productId: "JF-25", publisher: "Jaleco", releaseDate: "12/21/1989", alias: "Lord of King, The" },
  "famicom-lost-word-of-jenny": { productId: "TFC-JN", publisher: "Takara", releaseDate: "03/25/1987" },
  "famicom-lot-lot": { productId: "GTS-LL", publisher: "Tokuma Shoten / Irem", releaseDate: "12/21/1985" },
  "famicom-lunar-ball": { productId: "PNF-LB", publisher: "Pony Canyon / AII", releaseDate: "1985-05-12 00:00:00" },
  "famicom-mach-rider": { productId: "HVC-MR", publisher: "Nintendo", releaseDate: "11/21/1985" },
  "famicom-mad-city": { productId: "KDS-MU", publisher: "Konami", releaseDate: "1988-12-08 00:00:00" },
  "famicom-magic-candle": { productId: "SAC-1Q", publisher: "Sammy", releaseDate: "1992-06-03 00:00:00", alias: "Magic Candle, The" },
  "famicom-magic-darts": { productId: "KKS-4R", publisher: "Seta", releaseDate: "04/26/1991" },
  "famicom-magic-john": { productId: "JF-30", publisher: "Jaleco", releaseDate: "09/28/1990" },
  "famicom-magical-doropie": { productId: "VIC-VP", publisher: "Vic Tokai", releaseDate: "12/14/1990" },
  "famicom-magmax": { productId: "NBF-MM, 01", publisher: "Nichibutsu", releaseDate: "03/19/1986" },
  "famicom-maharaja": { productId: "SUN-MHA-6200", publisher: "Sunsoft", releaseDate: "09/29/1989" },
  "famicom-mahjong": { productId: "HVC-MJ", publisher: "Nintendo", releaseDate: "08/27/1983" },
  "famicom-mahjong-taikai": { productId: "KOE-IQ", publisher: "Koei", releaseDate: "10/31/1989" },
  "famicom-mahjong-taisen": { productId: "NBF-BJ", publisher: "Nichibutsu", releaseDate: "05/20/1992" },
  "famicom-maison-ikkoku": { productId: "BTC-M1", publisher: "Bothtec", releaseDate: "07/21/1988" },
  "famicom-majabencha-mahjong-senki": { productId: "GTS-VZ", publisher: "Tokuma Soft", releaseDate: "10/19/1990" },
  "famicom-majin-eiyuuden-wataru-gaiden": { productId: "HFC-V2", publisher: "Hudson Soft", releaseDate: "03/23/1990" },
  "famicom-major-league": { productId: "IF-13", publisher: "Irem", releaseDate: "10/27/1989" },
  "famicom-makaimura": { productId: "CAP-MK", publisher: "Capcom", releaseDate: "06/13/1986" },
  "famicom-maniac-mansion": { productId: "JF-18", publisher: "Jaleco", releaseDate: "09/13/1988" },
  "famicom-mappy": { productId: "NMP-4500, 04", publisher: "Namco", releaseDate: "11/14/1984" },
  "famicom-mappy-kids": { productId: "NAM-FMK-5800", publisher: "Namco", releaseDate: "12/22/1989" },
  "famicom-mappy-land": { productId: "NAM-ML-3900", publisher: "Namco", releaseDate: "11/26/1986" },
  "famicom-mario-bros": { productId: "HVC-MA", publisher: "Nintendo", releaseDate: "1983-09-09 00:00:00" },
  "famicom-mario-open-golf": { productId: "HVC-UG", publisher: "Nintendo", releaseDate: "09/20/1991" },
  "famicom-marusa-no-onna": { productId: "CAP-FM", publisher: "Capcom", releaseDate: "09/19/1989" },
  "famicom-mashou": { productId: "IF-05", publisher: "Irem", releaseDate: "12/15/1986" },
  "famicom-matendouji": { productId: "BTC-7M", publisher: "Quest", releaseDate: "08/24/1990" },
  "famicom-meiji-ishin": { productId: "USE-NC", publisher: "Use", releaseDate: "09/29/1989", alias: "Meijiishin" },
  "famicom-meikyuu-jima": { productId: "IF-18", publisher: "Irem", releaseDate: "06/29/1990" },
  "famicom-meimon-daisan-yakyuubu": { productId: "BA-DAI3", publisher: "Bandai", releaseDate: "1989-08-08 00:00:00", alias: "Meimon! Dai San Yakyuu Bu" },
  "famicom-meitantei-holmes-m-kara-no-chousenjou": { productId: "TCC-M3", publisher: "Towa Chiki", releaseDate: "1989-01-05 00:00:00", alias: "Mei Tantei Holmes: M Kara no Chousenjou" },
  "famicom-metal-flame-psy-buster": { productId: "DCE-QM", publisher: "Jaleco / Sculptured Software", releaseDate: "12/14/1990", alias: "Metal Flame PsyBuster" },
  "famicom-metal-gear": { productId: "KDS-ME", publisher: "Konami", releaseDate: "12/22/1987" },
  "famicom-metal-max": { productId: "DFC-26", publisher: "Data East / Crea-Tech", releaseDate: "05/24/1991" },
  "famicom-metal-slader-glory": { productId: "HAL-4J", publisher: "HAL Laboratories / *Yoshimiru", releaseDate: "08/30/1991" },
  "famicom-metro-cross": { productId: "NAM-MC-3900", publisher: "Namco", releaseDate: "12/16/1986" },
  "famicom-mickey-mouse-fushigi-no-kuni-no-daibouken": { productId: "HFC-MI", publisher: "Hudson Soft", releaseDate: "1987-06-03 00:00:00" },
  "famicom-mighty-bomb-jack": { productId: "TCF-MB", publisher: "Tecmo", releaseDate: "04/24/1986" },
  "famicom-mighty-final-fight": { productId: "CAP-SD", publisher: "Capcom", releaseDate: "1993-11-06 00:00:00" },
  "famicom-mike-tyson%27s-punch-out": { productId: "HVC-PT", publisher: "Nintendo", releaseDate: "11/21/1987" },
  "famicom-millipede": { productId: "HAL-ML", publisher: "HAL Laboratories / Atari", releaseDate: "1987-01-10 00:00:00" },
  "famicom-mindseeker": { productId: "NAM-MS-6500", publisher: "Namco", releaseDate: "04/18/1989" },
  "famicom-mini-putt": { productId: "WAV-Q6", publisher: "A wave", releaseDate: "02/15/1991" },
  "famicom-minna-no-tabou-no-nakayoshi-daisakusen": { productId: "CTS-9N", publisher: "Character Soft / ASCII", releaseDate: "11/22/1991", alias: "Minna no Taabou no Nakayoshi Daisakusen" },
  "famicom-miracle-ropit%27s-adventure-in-2100": { productId: "KIN-GM", publisher: "King Records / Animation 20", releaseDate: "1987-07-08 00:00:00" },
  "famicom-mirai-senshi-lios": { productId: "PAC-R6", publisher: "Pack-In-Video", releaseDate: "1989-01-12 00:00:00" },
  "famicom-mirai-shinwa-jarvas": { productId: "11", publisher: "Taito", releaseDate: "06/30/1987" },
  "famicom-mitsume-ga-tooru": { productId: "TOM-3M", publisher: "Tomy", releaseDate: "07/17/1992" },
  "famicom-mizushima-shinji-no-dai-koushien": { productId: "STE-VC", publisher: "Capcom", releaseDate: "10/26/1990" },
  "famicom-moai-kun": { productId: "KDS-M9", publisher: "Konami", releaseDate: "1990-09-03 00:00:00" },
  "famicom-moe-pro-saikyou-hen": { productId: "JF-33", publisher: "Jaleco", releaseDate: "11/22/1991" },
  "famicom-moero-judo-warriors": { productId: "JF-28", publisher: "Jaleco", releaseDate: "06/29/1990", alias: "Moero!! Juudou Warriors" },
  "famicom-moero-pro-soccer": { productId: "JF-21", publisher: "Jaleco", releaseDate: "12/23/1988" },
  "famicom-moero-pro-tennis": { productId: "JF-17", publisher: "Jaleco", releaseDate: "04/15/1988" },
  "famicom-moero-pro-yakyuu": { productId: "JF-13", publisher: "Jaleco", releaseDate: "06/26/1987" },
  "famicom-moeru-oniisan": { productId: "THF-M7", publisher: "Toho / NTV", releaseDate: "1989-08-08 00:00:00" },
  "famicom-momotarou-densetsu-gaiden": { productId: "HFC-MV", publisher: "Hudson Soft / Summer Project", releaseDate: "12/17/1993", alias: "Momotaro Densetsu Gaiden" },
  "famicom-momotarou-densetsu-peach-boy-legend": { productId: "HFC-MO", publisher: "Hudson Soft", releaseDate: "10/26/1987" },
  "famicom-momotarou-dentetsu": { productId: "HFC-M2", publisher: "Hudson Soft", releaseDate: "1988-02-12 00:00:00" },
  "famicom-money-game-ii": { productId: "SFL-MY", publisher: "Sofel", releaseDate: "1988-10-08 00:00:00", alias: "Money Game, The" },
  "famicom-monopoly": { productId: "TOM-6B", publisher: "Tomy", releaseDate: "1991-01-11 00:00:00" },
  "famicom-moon-crystal": { productId: "HCT-MS/017", publisher: "Hect", releaseDate: "08/28/1992" },
  "famicom-morita-shougi": { productId: "KKS-MC, 02", publisher: "Seta", releaseDate: "04/14/1987" },
  "famicom-mother": { productId: "HVC-MX", publisher: "Nintendo", releaseDate: "07/27/1989" },
  "famicom-motocross-champion": { productId: "KDS-CX", publisher: "Konami", releaseDate: "01/27/1989" },
  "famicom-mottomo-abunai-deka": { productId: "TDF-93", publisher: "Toei Animation / NTV", releaseDate: "1990-06-02 00:00:00" },
  "famicom-mouryou-senki-madara": { productId: "RC846", publisher: "Konami", releaseDate: "03/30/1990" },
  "famicom-musashi-no-bouken": { productId: "SEI-IC", publisher: "Sigma", releaseDate: "12/22/1990" },
  "famicom-nakajima-satoru-f-1-hero": { productId: "VRE-F1", publisher: "Varie", releaseDate: "1988-09-12 00:00:00" },
  "famicom-nakayoshi-to-issho": { productId: "SHI-MN", publisher: "Yutaka", releaseDate: "1993-10-12 00:00:00" },
  "famicom-namco-classic": { productId: "NAM-NC-5900", publisher: "Namco", releaseDate: "05/27/1988" },
  "famicom-namco-classic-ii": { productId: "NAM-FN2-5900", publisher: "Namco", releaseDate: "03/13/1992" },
  "famicom-nangoku-shirei-spy-vs-spy": { productId: "KSC-SI", publisher: "Kemco", releaseDate: "03/27/1987" },
  "famicom-nantettatte-baseball": { productId: "SUN-NTB-5900", publisher: "Sunsoft", releaseDate: "10/26/1990" },
  "famicom-napoleon-senki": { productId: "IF-09", publisher: "Irem", releaseDate: "03/18/1988" },
  "famicom-navy-blue": { productId: "IMX-NB", publisher: "I'Max / I'Max and Use", releaseDate: "02/14/1992" },
  "famicom-nekketsu-kakutou-densetsu": { productId: "TJC-NA", publisher: "Technos Japan", releaseDate: "12/23/1992" },
  "famicom-nekketsu-kouha-kunio-kun": { productId: "TJC-KN", publisher: "Technos Japan", releaseDate: "04/17/1987" },
  "famicom-nekketsu-koukou-dodgeball": { productId: "TJC-ND", publisher: "Technos Japan", releaseDate: "07/26/1988", alias: "Nekketsu Koukou Dodgeball-bu" },
  "famicom-nemo-pajama-hero": { productId: "CAP-EZ", publisher: "Capcom", releaseDate: "1990-07-12 00:00:00" },
  "famicom-new-ghostbusters-ii": { productId: "HAL-QD", publisher: "HAL Laboratories", releaseDate: "12/26/1990" },
  "famicom-new-york-nyankies": { productId: "ALT-7A", publisher: "Atlus", releaseDate: "1991-05-04 00:00:00" },
  "famicom-ninja-cop-saizou": { productId: "KYG-NX", publisher: "Kyugo / A.I", releaseDate: "11/17/1989" },
  "famicom-ninja-crusaders": { productId: "SAC-N4", publisher: "Sammy", releaseDate: "12/14/1990" },
  "famicom-ninja-jajamaru-kun": { productId: "JF-06", publisher: "Jaleco", releaseDate: "11/15/1985" },
  "famicom-ninja-jajamaru-kun-ginga-daisakusen": { productId: "JF-32", publisher: "Jaleco", releaseDate: "03/29/1991", alias: "Ninja Jajamaru: Ginga Daisakusen" },
  "famicom-ninja-kun-ashura-no-shou": { productId: "UPL-NJ", publisher: "UPL", releaseDate: "05/27/1988" },
  "famicom-ninja-kun-majou-no-bouken": { productId: "JF-03", publisher: "Jaleco", releaseDate: "1985-10-05 00:00:00" },
  "famicom-ninja-ryukenden": { productId: "TCF-NY, 07", publisher: "Tecmo", releaseDate: "1988-09-12 00:00:00" },
  "famicom-ninjara-hoi": { productId: "HSP-34", publisher: "ASCII / Login Soft", releaseDate: "1990-08-08 00:00:00" },
  "famicom-nippon-ichi-no-meikantoku": { productId: "ASM-M8", publisher: "Asmik", releaseDate: "1990-10-08 00:00:00", alias: "Nihon Ichi no Meikantoku" },
  "famicom-nobunaga-no-yabou-bushou-fuunroku": { productId: "KOE-IZ", publisher: "Koei", releaseDate: "12/21/1991", alias: "Nobunaga no Yabou: Bushou Fuuunroku" },
  "famicom-nobunaga-no-yabou-sengoku-gunyuuden": { productId: "KOE-NU", publisher: "Koei", releaseDate: "1990-03-02 00:00:00" },
  "famicom-nobunaga-no-yabou-zenkokuban": { productId: "KOE-NZ", publisher: "Koei", releaseDate: "03/18/1988" },
  "famicom-north-&amp;-south": { productId: "KSC-N5", publisher: "Kemco", releaseDate: "09/21/1990" },
  "famicom-nuts-&amp;-milk": { productId: "HFC-NM", publisher: "Hudson Soft", releaseDate: "07/28/1984" },
  "famicom-obocchama-kun": { productId: "TCF-3Q", publisher: "Tecmo", releaseDate: "1991-05-04 00:00:00" },
  "famicom-ochin-ni-toshi-puzzle-tonjan": { productId: "NMK-JT", publisher: "Jaleco / KK N.M.K.", releaseDate: "09/29/1989" },
  "famicom-oeka-kids-anpanman-to-oekaki-shiyou": { productId: "BA-OEKA1", publisher: "Bandai", releaseDate: "10/25/1990" },
  "famicom-oishinbo": { productId: "SHI-OS", publisher: "Shinsei", releaseDate: "07/25/1989" },
  "famicom-onyanko-town": { productId: "PNF-OT (R49V5901)", publisher: "Pony Canyon", releaseDate: "11/21/1985" },
  "famicom-operation-wolf": { productId: "TFC-OW, 24", publisher: "Taito", releaseDate: "03/31/1989" },
  "famicom-osomatsu-kun": { productId: "SHI-OB", publisher: "Shinsei", releaseDate: "1989-08-12 00:00:00" },
  "famicom-othello": { productId: "KWD-OH", publisher: "Kawada / HAL Laboratory", releaseDate: "11/13/1986" },
  "famicom-outlanders": { productId: "VFR-A1", publisher: "Victor Musical", releaseDate: "1987-04-12 00:00:00" },
  "famicom-over-horizon": { productId: "GAM-Z6", publisher: "Hot-B", releaseDate: "04/26/1991" },
  "famicom-pac-land": { productId: "NPL-4500, 10", publisher: "Namco", releaseDate: "11/21/1985" },
  "famicom-pac-man": { productId: "NPM-4500, 02", publisher: "Namco", releaseDate: "1984-02-11 00:00:00" },
  "famicom-pachi-com": { productId: "TFS-PC", publisher: "Toemiland / Toshiba EMI/J.P.M.", releaseDate: "11/21/1985" },
  "famicom-pachinko-daisakusen": { productId: "CDS-81", publisher: "Coconuts / C-Dream", releaseDate: "07/19/1991" },
  "famicom-pachinko-daisakusen-2": { productId: "CDS-82", publisher: "Coconuts / C-Dream", releaseDate: "1992-10-07 00:00:00" },
  "famicom-pachio-kun-2": { productId: "CDS-P2", publisher: "Coconuts / C-Dream", releaseDate: "01/30/1989" },
  "famicom-pachio-kun-3": { productId: "CDS-P3", publisher: "C-Dream", releaseDate: "10/26/1990" },
  "famicom-pachio-kun-4": { productId: "CDS-B4", publisher: "Coconuts", releaseDate: "11/22/1991" },
  "famicom-pachio-kun-5": { productId: "CDS-PE", publisher: "Coconuts / C-Dream", releaseDate: "06/18/1993" },
  "famicom-palamedes": { productId: "GAM-JI", publisher: "Hot-B", releaseDate: "1990-06-07 00:00:00" },
  "famicom-paperboy": { productId: "ALT-7B", publisher: "Altron", releaseDate: "01/30/1991" },
  "famicom-parareru-world": { productId: "VRE-R9", publisher: "Varie", releaseDate: "1990-10-08 00:00:00" },
  "famicom-parasol-henbee": { productId: "EPO-E6", publisher: "Epoch", releaseDate: "02/15/1991" },
  "famicom-paris-dakar-rally-special": { productId: "CBS-PD", publisher: "CBS/Sony", releaseDate: "1988-01-02 00:00:00" },
  "famicom-parodius-da": { productId: "KON-RC849", publisher: "Konami", releaseDate: "11/30/1990" },
  "famicom-peepar-time": { productId: "SAN-P6", publisher: "Sanritsu", releaseDate: "1990-10-08 00:00:00" },
  "famicom-penguin-kun-wars": { productId: "HSP-03", publisher: "ASCII", releaseDate: "12/25/1985" },
  "famicom-perfect-bowling": { productId: "TKS-G8", publisher: "Tonkin House", releaseDate: "07/25/1989" },
  "famicom-pinball": { productId: "HVC-PN", publisher: "Nintendo", releaseDate: "1984-02-02 00:00:00" },
  "famicom-pinball-quest": { productId: "JF-26", publisher: "Jaleco", releaseDate: "12/15/1989" },
  "famicom-pizza-pop": { productId: "JF-35", publisher: "Jaleco", releaseDate: "1992-07-01 00:00:00" },
  "famicom-plasma-ball": { productId: "JF-36", publisher: "Jaleco", releaseDate: "03/27/1992" },
  "famicom-pooyan": { productId: "HFC-PO", publisher: "Hudson Soft / Konami", releaseDate: "09/20/1985" },
  "famicom-popeye": { productId: "HVC-PP", publisher: "Nintendo", releaseDate: "07/15/1983" },
  "famicom-popeye-no-eigo-asobi": { productId: "HVC-EN", publisher: "Nintendo", releaseDate: "11/22/1983" },
  "famicom-portopia-renzoku-satsujin-jiken": { productId: "EFC-PR", publisher: "Enix", releaseDate: "11/29/1985" },
  "famicom-power-blazer": { productId: "TFC-PB, 31", publisher: "Taito", releaseDate: "04/20/1990" },
  "famicom-power-soccer": { productId: "GTS-FT", publisher: "Tokuma Soft", releaseDate: "03/30/1990" },
  "famicom-predator": { productId: "PAC-PL", publisher: "Pack-In-Video", releaseDate: "1988-10-03 00:00:00" },
  "famicom-president-no-sentaku": { productId: "GAM-83-06", publisher: "Hot-B", releaseDate: "1990-02-03 00:00:00" },
  "famicom-pro-yakyuu-family-stadium": { productId: "NAM-FS-3900", publisher: "Namco", releaseDate: "1986-10-12 00:00:00" },
  "famicom-pro-yakyuu-family-stadium-%2787": { productId: "NAM-FS87-3900", publisher: "Namco", releaseDate: "12/22/1987" },
  "famicom-pro-yakyuu-family-stadium-%2788": { productId: "NAM-FS88-4900", publisher: "Namco", releaseDate: "12/20/1988" },
  "famicom-pro-yakyuu-satsujin-jiken": { productId: "CAP-PV", publisher: "Capcom", releaseDate: "12/24/1988" },
  "famicom-puyo-puyo": { productId: "TIM-PY", publisher: "Tokuma Shoten / Compile", releaseDate: "07/23/1993" },
  "famicom-puzslot": { productId: "SAC-1P", publisher: "Sammy", releaseDate: "02/28/1992" },
  "famicom-puzznic": { productId: "IGS-9U", publisher: "IGS", releaseDate: "07/19/1991" },
  "famicom-pyokotan-no-dai-meiro": { productId: "SUN-PYK-4980", publisher: "Sunsoft", releaseDate: "03/19/1993" },
  "famicom-quarter-back-scramble": { productId: "PNF-QS (R59V5925)", publisher: "Pony Canyon", releaseDate: "12/19/1989" },
  "famicom-quarth": { productId: "KDS-H7", publisher: "Konami", releaseDate: "04/13/1990" },
  "famicom-quinty": { productId: "NAM-QT-4900", publisher: "Namco", releaseDate: "06/27/1989" },
  "famicom-raf-world": { productId: "TEC-RF", publisher: "Sunsoft / Tokai Engineering", releaseDate: "1990-10-08 00:00:00" },
  "famicom-raid-on-bungeling-bay": { productId: "HFC-RB", publisher: "Hudson Soft", releaseDate: "02/22/1985" },
  "famicom-rambo": { productId: "PAC-RV", publisher: "Pack-In-Video", releaseDate: "1987-04-12 00:00:00" },
  "famicom-rampart": { productId: "KDS-73", publisher: "Konami", releaseDate: "11/29/1991" },
  "famicom-rasaaru-ishii-no-childs-quest": { productId: "NAM-CQ-5500", publisher: "Namco", releaseDate: "06/23/1989" },
  "famicom-recca": { productId: "NAX-RE", publisher: "Naxat Soft", releaseDate: "07/17/1992" },
  "famicom-red-arremer-ii": { productId: "CAP-1L", publisher: "Capcom", releaseDate: "07/17/1992" },
  "famicom-reigen-doushi": { productId: "PNF-KY (R59V5917)", publisher: "Pony Canyon", releaseDate: "09/16/1988" },
  "famicom-ripple-island": { productId: "TEC-RI", publisher: "Sunsoft", releaseDate: "01/23/1988" },
  "famicom-road-fighter": { productId: "RC801", publisher: "Konami", releaseDate: "1985-11-07 00:00:00" },
  "famicom-robocco-wars": { productId: "IGS-X9", publisher: "IGS", releaseDate: "1991-02-08 00:00:00" },
  "famicom-robocop": { productId: "DFC-CP", publisher: "Data East", releaseDate: "08/25/1989" },
  "famicom-robocop-2": { productId: "DFC-2C", publisher: "Data East", releaseDate: "1991-02-04 00:00:00" },
  "famicom-rockman": { productId: "CAP-RX", publisher: "Capcom", releaseDate: "12/17/1987" },
  "famicom-rokudenashi-blues": { productId: "28", publisher: "Bandai", releaseDate: "10/29/1993" },
  "famicom-rollerball": { productId: "HAL-RH", publisher: "HAL Laboratories", releaseDate: "12/20/1988" },
  "famicom-rolling-thunder": { productId: "NAM-RT-5500", publisher: "Namco", releaseDate: "03/17/1989" },
  "famicom-romancia": { productId: "TKS-G2", publisher: "Tokyo Sheseki", releaseDate: "10/30/1987" },
  "famicom-route-16-turbo": { productId: "SUN-R16-4900", publisher: "Sunsoft", releaseDate: "1985-04-10 00:00:00" },
  "famicom-royal-blood": { productId: "KOE-IU", publisher: "Koei", releaseDate: "08/29/1991" },
  "famicom-sabaku-no-kitsume": { productId: "KSC-DF", publisher: "Kemco", releaseDate: "04/28/1988" },
  "famicom-saint-seiya-ougon-densetsu": { productId: "BA-SEIYA", publisher: "Bandai", releaseDate: "1987-10-08 00:00:00" },
  "famicom-saint-seiya-ougon-densetsu-kanketsu-hen": { productId: "SHI-OK", publisher: "Shinsei", releaseDate: "05/30/1988" },
  "famicom-saiyuuki-world": { productId: "NMK-KW", publisher: "Jaleco / KK N.M.K.", releaseDate: "1988-11-11 00:00:00" },
  "famicom-salad-no-kuni-no-tomato-hime": { productId: "HFC-RT", publisher: "Hudson Soft", releaseDate: "05/27/1988" },
  "famicom-salamander": { productId: "KON-RC821", publisher: "Konami", releaseDate: "09/25/1987" },
  "famicom-samsara-naga": { productId: "VFR-Q1-08", publisher: "Victor Musical", releaseDate: "03/23/1990" },
  "famicom-sanada-juu-yuushi": { productId: "KSC-JY", publisher: "Kemco", releaseDate: "06/27/1988" },
  "famicom-sangokushi": { productId: "KOE-IS", publisher: "Koei", releaseDate: "10/30/1988" },
  "famicom-sangokushi-chuugen-no-hasha": { productId: "NAM-ST-6900", publisher: "Namco", releaseDate: "07/29/1988" },
  "famicom-sangokushi-ii": { productId: "KOE-XL", publisher: "Koei", releaseDate: "1990-02-11 00:00:00" },
  "famicom-sangokushi-ii-haou-no-tairiku": { productId: "NAM-FS2-6900", publisher: "Namco", releaseDate: "1992-10-06 00:00:00" },
  "famicom-sanma-no-mei-tantei": { productId: "NAM-SM-4900", publisher: "Namco", releaseDate: "1987-02-04 00:00:00" },
  "famicom-sanrio-carnival": { productId: "CTS-ZV", publisher: "Character Soft", releaseDate: "11/22/1990" },
  "famicom-sanrio-carnival-2": { productId: "CTS-SQ", publisher: "Character Soft", releaseDate: "01/14/1993" },
  "famicom-sanrio-cup-pon-pon-volley": { productId: "CTS-PM", publisher: "Character Soft", releaseDate: "07/17/1992" },
  "famicom-satomi-hakkenden": { productId: "SFX-S8", publisher: "SNK Electronics", releaseDate: "01/20/1989" },
  "famicom-sd-gundam-gaiden-knight-gundam-monogatari": { productId: "BA-KGD", publisher: "Bandai", releaseDate: "1990-11-08 00:00:00" },
  "famicom-sd-gundam-gaiden-knight-gundam-monogatari-2": { productId: "BA-KGD2", publisher: "Bandai", releaseDate: "1991-12-10 00:00:00", alias: "SD Gundam Gaiden: Knight Gundam Monogatari 2: Hikari no Kishi" },
  "famicom-sd-hero-soukessen-taose-aku-no-gundan": { productId: "BAP-X5", publisher: "Banpresto", releaseDate: "1990-07-07 00:00:00" },
  "famicom-sd-keiji-blader": { productId: "TFC-SKB-6400-39", publisher: "Taito", releaseDate: "1991-02-08 00:00:00" },
  "famicom-sd-sangoku-bushou-retsuden": { productId: "BAP-X6", publisher: "Banpresto", releaseDate: "1990-08-09 00:00:00" },
  "famicom-seicross": { productId: "NBF-SE", publisher: "Nichibutsu", releaseDate: "05/15/1986" },
  "famicom-seikima-ii-akuma-no-gyakushuu": { productId: "CBS-SA, 49FR-1", publisher: "CBS/Sony", releaseDate: "12/25/1986" },
  "famicom-seirei-densetsu-lickle": { productId: "DTF-LK", publisher: "Taito", releaseDate: "06/26/1992" },
  "famicom-seirei-gari": { productId: "HFC-V1", publisher: "Hudson Soft", releaseDate: "1989-08-12 00:00:00" },
  "famicom-sekiryuuou": { productId: "TEC-AJ", publisher: "Sunsoft / Tokai Engineering", releaseDate: "1989-10-02 00:00:00" },
  "famicom-senjou-no-ookami": { productId: "CAP-SJ", publisher: "Capcom", releaseDate: "09/27/1986" },
  "famicom-shadow-brain": { productId: "R98V5934 (PNF-9S)", publisher: "Pony Canyon", releaseDate: "03/21/1991" },
  "famicom-shadowgate": { productId: "KSC-3S", publisher: "Kemco / Icom Simulations", releaseDate: "03/31/1989" },
  "famicom-shanghai": { productId: "SUN-SS9-5300", publisher: "Sunsoft / Activision", releaseDate: "1987-04-12 00:00:00" },
  "famicom-shanghai-ii": { productId: "TEC-XT", publisher: "Sunsoft", releaseDate: "08/24/1990" },
  "famicom-shin-jinrui-the-new-type": { productId: "RES-SG", publisher: "Rix Soft", releaseDate: "1987-10-02 00:00:00" },
  "famicom-shin-moero-pro-yakyuu": { productId: "JF-23", publisher: "Jaleco", releaseDate: "07/13/1989" },
  "famicom-shinsenden": { productId: "IF-16, TIX-Z3", publisher: "Irem", releaseDate: "12/15/1989" },
  "famicom-shogi-meikan-%2792": { productId: "HCT-I9", publisher: "Hect", releaseDate: "01/30/1992" },
  "famicom-shogi-meikan-%2793": { productId: "HCT-IJ/019", publisher: "Hect", releaseDate: "1992-04-12 00:00:00" },
  "famicom-shogun": { productId: "HCT-HD", publisher: "Hect", releaseDate: "05/27/1988" },
  "famicom-shuffle-fight": { productId: "BAP-CB", publisher: "Banpresto", releaseDate: "1992-09-10 00:00:00" },
  "famicom-shufflepuck-cafe": { productId: "PHF-XP", publisher: "Broderbund", releaseDate: "10/21/1990" },
  "famicom-side-pocket": { productId: "NAM-SP-3900", publisher: "Namco", releaseDate: "10/30/1987" },
  "famicom-silva-saga": { productId: "KKS-SR", publisher: "Seta", releaseDate: "07/24/1992" },
  "famicom-sky-destroyer": { productId: "5", publisher: "Taito", releaseDate: "11/14/1985" },
  "famicom-sky-kid": { productId: "NSK-3900, 18", publisher: "Namco", releaseDate: "08/22/1986" },
  "famicom-snow-bros": { productId: "TOA-7L", publisher: "Toaplan", releaseDate: "1991-06-12 00:00:00" },
  "famicom-soccer": { productId: "HVC-SC", publisher: "Nintendo", releaseDate: "1985-09-04 00:00:00" },
  "famicom-soccer-league-winner%27s-cup": { productId: "DFC-WN", publisher: "Data East", releaseDate: "1988-12-08 00:00:00" },
  "famicom-softball-tengoku": { productId: "TKS-G9", publisher: "Tonkin House", releaseDate: "10/27/1989" },
  "famicom-solomon-no-kagi": { productId: "TCF-SK, 02", publisher: "Tecmo", releaseDate: "07/30/1986" },
  "famicom-solstice": { productId: "ESF-E3", publisher: "Epic/Sony Records", releaseDate: "07/20/1990" },
  "famicom-son-son": { productId: "CAP-SS", publisher: "Capcom", releaseDate: "1986-08-02 00:00:00" },
  "famicom-space-harrier": { productId: "TFC-S0", publisher: "Takara / Sega", releaseDate: "1989-06-01 00:00:00" },
  "famicom-space-hunter": { productId: "KSC-HT", publisher: "Kemco", releaseDate: "09/25/1986" },
  "famicom-space-invaders": { productId: "1", publisher: "Taito", releaseDate: "04/17/1985" },
  "famicom-spartan-x": { productId: "HVC-SX", publisher: "Nintendo / Irem", releaseDate: "06/21/1985" },
  "famicom-spartan-x-2": { productId: "IF-23", publisher: "Irem", releaseDate: "09/27/1991" },
  "famicom-spelunker": { productId: "IF-03", publisher: "Irem / Broderbund", releaseDate: "1985-07-12 00:00:00" },
  "famicom-spot": { productId: "BPS-BI", publisher: "Bullet-Proof Software", releaseDate: "10/16/1992" },
  "famicom-spy-vs-spy": { productId: "KSC-SP", publisher: "Kemco", releaseDate: "04/26/1986" },
  "famicom-sqoon": { productId: "IF-04", publisher: "Irem / Home Data", releaseDate: "06/26/1986" },
  "famicom-star-force": { productId: "HFC-SF", publisher: "Hudson Soft / Tehkan", releaseDate: "06/25/1985" },
  "famicom-star-gate": { productId: "HAL-SB", publisher: "HAL Laboratories / HAL Laboratories", releaseDate: "09/24/1987" },
  "famicom-star-luster": { productId: "NSL-4900, 12", publisher: "Namco", releaseDate: "1985-06-12 00:00:00" },
  "famicom-star-soldier": { productId: "HFC-SO", publisher: "Hudson Soft / Momo", releaseDate: "06/13/1986" },
  "famicom-star-wars": { productId: "VFR-7V", publisher: "Victor Musical", releaseDate: "11/15/1991" },
  "famicom-star-wars-empire-strikes-back": { productId: "VFR-8V", publisher: "Victor Musical", releaseDate: "1993-12-03 00:00:00", alias: "Star Wars: The Empire Strikes Back" },
  "famicom-sted-iseki-wakusei-no-yabou": { productId: "KAC-3E", publisher: "K. Amusement", releaseDate: "1990-03-08 00:00:00" },
  "famicom-sukeban-deka-iii": { productId: "TDF-KJ", publisher: "Toei Animation", releaseDate: "01/22/1988" },
  "famicom-super-arabian": { productId: "SUN-SA-4500", publisher: "Sunsoft", releaseDate: "07/25/1985" },
  "famicom-super-black-onyx": { productId: "BPS-OX", publisher: "Bullet-Proof Software", releaseDate: "07/14/1988" },
  "famicom-super-chinese": { productId: "NSC-4900, 15", publisher: "Namco / Micro Academy", releaseDate: "06/20/1986" },
  "famicom-super-chinese-3": { productId: "CBF-3c", publisher: "Culture Brain", releaseDate: "1991-01-03 00:00:00" },
  "famicom-super-dyna%27mix-badminton": { productId: "VAP-BN", publisher: "Vap", releaseDate: "08/26/1988" },
  "famicom-super-mario-bros": { productId: "HVC-SM", publisher: "Nintendo", releaseDate: "09/13/1985" },
  "famicom-super-mario-bros-3": { productId: "HVC-UM", publisher: "Nintendo", releaseDate: "10/23/1988" },
  "famicom-super-mario-usa": { productId: "HVC-MT", publisher: "Nintendo", releaseDate: "09/14/1992" },
  "famicom-super-moguratataki-pokkun-mogura": { productId: "IGS-X1", publisher: "IGS", releaseDate: "1989-08-12 00:00:00" },
  "famicom-super-momotarou-dentetsu": { productId: "HFC-3X", publisher: "Hudson Soft", releaseDate: "03/20/1992" },
  "famicom-super-pinball": { productId: "CDS-PJ", publisher: "C-Dream", releaseDate: "08/23/1988" },
  "famicom-super-pitfall": { productId: "PNF-PF", publisher: "Pony Canyon / Activision", releaseDate: "1986-05-09 00:00:00" },
  "famicom-super-real-baseball-%2788": { productId: "VAP-BG", publisher: "Vap", releaseDate: "07/30/1988" },
  "famicom-super-rugby": { productId: "TSS-S7", publisher: "TSS", releaseDate: "12/27/1989" },
  "famicom-super-sprint": { productId: "ALT-7C", publisher: "Altron / Atari", releaseDate: "1991-03-08 00:00:00" },
  "famicom-super-star-force": { productId: "TCF-ST", publisher: "Tecmo", releaseDate: "1986-11-11 00:00:00" },
  "famicom-super-star-prowrestling": { productId: "PNF-S9", publisher: "Pony Canyon", releaseDate: "1989-09-12 00:00:00", alias: "Superstar Pro Wrestling" },
  "famicom-superman": { productId: "KSC-SN", publisher: "Kemco", releaseDate: "12/26/1987" },
  "famicom-swat-special-weapons-and-tactics": { productId: "TDF-SW", publisher: "Toei Animation", releaseDate: "1987-11-09 00:00:00" },
  "famicom-sweet-home": { productId: "CAP-EH", publisher: "Capcom", releaseDate: "12/15/1989" },
  "famicom-sword-master": { productId: "ATH-ZU", publisher: "Athena", releaseDate: "12/21/1990" },
  "famicom-tag-team-pro-wrestling": { productId: "13", publisher: "Namco", releaseDate: "1986-02-04 00:00:00" },
  "famicom-taito-basketball": { productId: "DTF-UJ", publisher: "Disco / Taito", releaseDate: "04/26/1991" },
  "famicom-taito-chase-hq": { productId: "DTF-H9, 28", publisher: "Taito", releaseDate: "1989-08-12 00:00:00", alias: "Taito Chase H.Q." },
  "famicom-taiyou-no-yuusha-firebird": { productId: "IF-26, TIX-6Q", publisher: "Irem", releaseDate: "1992-11-01 00:00:00" },
  "famicom-takahashi-meijin-no-boukenjima": { productId: "HFC-TB", publisher: "Hudson Soft", releaseDate: "1986-12-09 00:00:00" },
  "famicom-takahashi-meijin-no-boukenjima-ii": { productId: "HFC-V7", publisher: "Hudson Soft", releaseDate: "04/26/1991" },
  "famicom-takahashi-meijin-no-boukenjima-iii": { productId: "HFC-4X", publisher: "Hudson Soft", releaseDate: "07/31/1992" },
  "famicom-takahashi-meijin-no-boukenjima-iv": { productId: "HFC-TT", publisher: "Hudson Soft", releaseDate: "06/24/1994" },
  "famicom-takahashi-meijin-no-bugutte-honey": { productId: "HFC-BH", publisher: "Hudson Soft", releaseDate: "1987-05-06 00:00:00" },
  "famicom-takeda-shingen": { productId: "GAM-HB-03", publisher: "Hot-B", releaseDate: "03/28/1988" },
  "famicom-takeda-shingen-2": { productId: "GAM-23-05", publisher: "Hot-B", releaseDate: "08/21/1989" },
  "famicom-takeshi-no-chousenjou": { productId: "9", publisher: "Taito", releaseDate: "1986-10-12 00:00:00" },
  "famicom-takeshi-no-sengoku-fuuunji": { productId: "TFC-TSF-5800-20", publisher: "Taito", releaseDate: "11/25/1988" },
  "famicom-tanigawa-kouji-no-shougi-shinan-ii": { productId: "PNF-T2 (R55V5914)", publisher: "Pony Canyon", releaseDate: "03/18/1988" },
  "famicom-tanigawa-kouji-no-shougi-shinan-iii": { productId: "PNF-T3", publisher: "Pony Canyon", releaseDate: "09/14/1989" },
  "famicom-tantei-jinguuji-saburou-toki-no-sugiyuku-mama-ni": { productId: "DFC-J4", publisher: "Data East", releaseDate: "09/28/1990" },
  "famicom-tao": { productId: "VAP-BY", publisher: "Vap", releaseDate: "1989-01-12 00:00:00" },
  "famicom-tashiro-masashi-no-princess-ga-ippai": { productId: "ESF-P0", publisher: "Epic / CBS/Sony", releaseDate: "10/27/1989" },
  "famicom-tatakai-no-banka": { productId: "CAP-TA", publisher: "Capcom", releaseDate: "12/24/1986" },
  "famicom-tecmo-bowl": { productId: "TCF-TW, 12", publisher: "Tecmo", releaseDate: "11/30/1990" },
  "famicom-tecmo-super-bowl": { productId: "TCF-4U, 18", publisher: "Tecmo", releaseDate: "12/13/1991" },
  "famicom-tecmo-world-cup-soccer": { productId: "Obo", publisher: "Tecmo", releaseDate: "1990-07-12 00:00:00" },
  "famicom-teenage-mutant-ninja-turtles": { productId: "RC853", publisher: "Konami", releaseDate: "1990-07-12 00:00:00" },
  "famicom-teenage-mutant-ninja-turtles-2-the-manhattan-project": { productId: "RC863", publisher: "Konami", releaseDate: "12/13/1991" },
  "famicom-tenka-no-goikenban-mito-koumon": { productId: "SUN-MK-5300", publisher: "Sunsoft", releaseDate: "1987-11-08 00:00:00" },
  "famicom-tenkaichi-bushi-keru-naguuru": { productId: "NAM-FKN-4900", publisher: "Namco", releaseDate: "07/21/1989" },
  "famicom-tennis": { productId: "HVC-TE", publisher: "Nintendo", releaseDate: "01/14/1984" },
  "famicom-terao-no-dosukoi-oozumou": { productId: "JF-24", publisher: "Jaleco", releaseDate: "11/24/1989" },
  "famicom-terra-cresta": { productId: "NBF-TC", publisher: "Nichibutsu", releaseDate: "09/27/1986" },
  "famicom-tetra-star-the-fighter": { productId: "DTF-YE, 37", publisher: "Taito", releaseDate: "05/24/1991" },
  "famicom-tetris": { productId: "BPS-T0", publisher: "Bullet-Proof Software", releaseDate: "12/22/1988" },
  "famicom-tetris-flash": { productId: "HVC-TR", publisher: "Nintendo", releaseDate: "09/21/1993" },
  "famicom-tetsudou-ou": { productId: "DBF-RW", publisher: "dB-Soft", releaseDate: "1987-12-12 00:00:00" },
  "famicom-tetsuwan-atom": { productId: "RC827", publisher: "Konami", releaseDate: "02/26/1988" },
  "famicom-thexder": { productId: "SQF-TX", publisher: "Square Soft / Game Arts", releaseDate: "12/19/1985" },
  "famicom-thunderbirds": { productId: "PAC-T5", publisher: "Pack-In-Video", releaseDate: "09/29/1989" },
  "famicom-tiger-heli": { productId: "PNF-TH", publisher: "Pony Canyon", releaseDate: "1986-05-12 00:00:00" },
  "famicom-time-zone": { productId: "SEI-1G", publisher: "Sigma", releaseDate: "10/25/1991" },
  "famicom-times-of-lore": { productId: "THF-U7", publisher: "Toho", releaseDate: "1990-07-12 00:00:00" },
  "famicom-tiny-toon-adventures": { productId: "RC860", publisher: "Konami", releaseDate: "12/20/1991" },
  "famicom-titan": { productId: "SFL-NL", publisher: "Sofel / Titus", releaseDate: "1990-10-08 00:00:00" },
  "famicom-tm-network-live-in-power-bowl": { productId: "ESF-T9", publisher: "CBS/Sony", releaseDate: "12/22/1989" },
  "famicom-toki-no-tabibito-time-stranger": { productId: "KSC-TS", publisher: "Kemco", releaseDate: "12/26/1986" },
  "famicom-tokkyuu-shirei-solbrain": { productId: "ANG-OM", publisher: "Angel", releaseDate: "10/26/1991", alias: "Tokkou Shirei Solbrain" },
  "famicom-tokoro-san-no-mamoru-mo-semeru-mo": { productId: "ESF-TO", publisher: "Epic/Sony Records", releaseDate: "06/27/1987" },
  "famicom-tokyo-pachi-slot-adventure": { productId: "CDS-83", publisher: "C-Dream", releaseDate: "12/13/1991" },
  "famicom-tom-&amp;-jerry": { productId: "ALT-5Y", publisher: "Altron", releaseDate: "11/13/1992" },
  "famicom-tom-sawyer-no-bouken": { productId: "KKS-YB", publisher: "Seta", releaseDate: "1989-06-02 00:00:00" },
  "famicom-top-gun": { productId: "KDS-TG", publisher: "Konami", releaseDate: "1987-11-12 00:00:00" },
  "famicom-top-gun-dual-fighters": { productId: "KDS-OG", publisher: "Konami", releaseDate: "12/15/1989" },
  "famicom-top-management": { productId: "KOE-XQ", publisher: "Koei", releaseDate: "1990-12-12 00:00:00" },
  "famicom-top-rider": { productId: "VRE-R1", publisher: "Varie", releaseDate: "12/17/1988" },
  "famicom-top-striker": { productId: "NAM-FTS-5800", publisher: "Namco", releaseDate: "10/22/1992" },
  "famicom-totsuzen-macho-man": { productId: "VIC-M5", publisher: "Vic Tokai", releaseDate: "1988-02-12 00:00:00" },
  "famicom-touhou-kenbun-roku": { productId: "NAT-N1", publisher: "Natsume", releaseDate: "1988-10-11 00:00:00" },
  "famicom-toukon-club": { productId: "JF-37", publisher: "Jaleco", releaseDate: "07/24/1992" },
  "famicom-tower-of-druaga": { productId: "NTD-4900, 07", publisher: "Namco", releaseDate: "1985-06-08 00:00:00", alias: "Tower of Druaga, The" },
  "famicom-tsuppari-oozumou": { productId: "TCF-TM", publisher: "Tecmo", releaseDate: "09/18/1987" },
  "famicom-tsuppari-wars": { productId: "SAC-7W", publisher: "Sammy", releaseDate: "06/28/1991" },
  "famicom-twin-eagle": { productId: "VIS-2E", publisher: "Visco", releaseDate: "1991-12-04 00:00:00" },
  "famicom-twinbee": { productId: "RC807", publisher: "Konami", releaseDate: "1986-04-01 00:00:00" },
  "famicom-uchuu-keibitai-sdf": { productId: "HAL-UI", publisher: "HAL Laboratories", releaseDate: "1990-07-09 00:00:00" },
  "famicom-uchuusen-cosmo-carrier": { productId: "JF-16", publisher: "Jaleco", releaseDate: "1987-06-11 00:00:00" },
  "famicom-ultima-kyoufu-no-exodus": { productId: "PNF-UL", publisher: "Pony Canyon", releaseDate: "1987-09-10 00:00:00" },
  "famicom-ultima-seija-e-no-michi": { productId: "PNF-US", publisher: "Pony Canyon / Origin", releaseDate: "09/20/1989" },
  "famicom-ultraman-club-kaijuu-dai-kessen": { productId: "ANG-UA", publisher: "Angel", releaseDate: "12/25/1992" },
  "famicom-united-states-presidential-race": { productId: "HCT-AQ/002", publisher: "Hect", releaseDate: "10/28/1988" },
  "famicom-untouchables": { productId: "ALT-U6", publisher: "Altron", releaseDate: "12/20/1991", alias: "Untouchables, The" },
  "famicom-urban-champion": { productId: "HVC-UC", publisher: "Nintendo", releaseDate: "11/14/1984" },
  "famicom-ushio-to-tora": { productId: "SHI-RA", publisher: "Yutaka", releaseDate: "1993-09-07 00:00:00" },
  "famicom-utsurundesu-kawauso-hawaii-e-iku": { productId: "TFC-U9", publisher: "Takara", releaseDate: "1992-06-03 00:00:00" },
  "famicom-venus-senki": { productId: "VRE-R2", publisher: "Varie", releaseDate: "10/14/1989" },
  "famicom-viva-las-vegas": { productId: "ESF-LV, 59-6R-2", publisher: "Epic / CBS/Sony", releaseDate: "09/30/1988" },
  "famicom-volguard-ii": { productId: "dBF-VL", publisher: "dB-Soft", releaseDate: "1985-07-12 00:00:00" },
  "famicom-wagyan-land": { productId: "NAM-WL-4900", publisher: "Namco", releaseDate: "1989-09-02 00:00:00" },
  "famicom-wagyan-land-2": { productId: "NAM-WL2-5800", publisher: "Namco", releaseDate: "12/14/1990" },
  "famicom-wagyan-land-3": { productId: "NAM-FW3-5800", publisher: "Namco", releaseDate: "1992-08-12 00:00:00" },
  "famicom-wanpaku-kokkun-no-gourmet-world": { productId: "DTF-WK, 43", publisher: "Taito", releaseDate: "04/24/1992" },
  "famicom-wario-no-mori": { productId: "HVC-UW", publisher: "Nintendo", releaseDate: "02/19/1994" },
  "famicom-warpman": { productId: "8", publisher: "Namco", releaseDate: "1985-12-07 00:00:00" },
  "famicom-western-kids": { productId: "VIS-5K", publisher: "Visco", releaseDate: "09/13/1991" },
  "famicom-wild-gunman": { productId: "HVC-WG", publisher: "Nintendo", releaseDate: "02/18/1984" },
  "famicom-willow": { productId: "CAP-WI", publisher: "Capcom", releaseDate: "07/18/1989" },
  "famicom-wing-of-madoola": { productId: "SUN-MAD-4900", publisher: "Sunsoft", releaseDate: "12/18/1986", alias: "Wing of Madoola, The" },
  "famicom-wit%27s": { productId: "ATH-XW", publisher: "Athena", releaseDate: "07/13/1990" },
  "famicom-woody-poco": { productId: "DBF-UP", publisher: "dB-Soft", releaseDate: "06/20/1987" },
  "famicom-world-boxing": { productId: "TSS-W7", publisher: "TSS", releaseDate: "1990-08-09 00:00:00" },
  "famicom-world-grand-prix-pole-to-finish": { productId: "DFC-FH", publisher: "Data East", releaseDate: "01/31/1989" },
  "famicom-world-super-tennis": { productId: "ASM-W1", publisher: "Asmik", releaseDate: "10/13/1989" },
  "famicom-wrecking-crew": { productId: "HVC-WR", publisher: "Nintendo", releaseDate: "06/18/1985" },
  "famicom-wwf-wrestle-mania-challenge": { productId: "GAM-W9", publisher: "Hot-B / Acclaim", releaseDate: "03/27/1992" },
  "famicom-xevious": { productId: "NXV-4900, 03", publisher: "Namco", releaseDate: "1984-08-11 00:00:00" },
  "famicom-yamamura-misa-suspense-kyouto-hana-no-misshitsu-satsujin-jiken": { productId: "22", publisher: "Taito", releaseDate: "1989-11-02 00:00:00" },
  "famicom-yamamura-misa-suspense-kyouto-ryuu-no-tera-satsujin-jiken": { productId: "TFC-KR-5500-14", publisher: "Taito", releaseDate: "1987-11-12 00:00:00" },
  "famicom-yamamura-misa-suspense-kyouto-zaiteku-satsujin-jiken": { productId: "HCT-QZ/008", publisher: "Hect", releaseDate: "1990-02-11 00:00:00" },
  "famicom-yie-ar-kung-fu": { productId: "RC802", publisher: "Konami", releaseDate: "04/22/1985" },
  "famicom-yoshi-no-cookie": { productId: "HVC-CI", publisher: "Nintendo", releaseDate: "11/21/1992" },
  "famicom-yoshi-no-tamago": { productId: "HVC-YO", publisher: "Nintendo", releaseDate: "12/14/1991" },
  "famicom-youkai-club": { productId: "JF-12", publisher: "Jaleco", releaseDate: "05/19/1987" },
  "famicom-youkai-douchuuki": { productId: "NAM-YD-4900", publisher: "Namco", releaseDate: "06/24/1988" },
  "famicom-ys": { productId: "VFR-Y2-05", publisher: "Victor Musical", releaseDate: "08/26/1988" },
  "famicom-yume-penguin-monogatari": { productId: "KDS-UB", publisher: "Konami", releaseDate: "01/25/1991" },
  "famicom-zenbi-pro-basketball": { productId: "VIC-A2", publisher: "Vic Tokai", releaseDate: "07/21/1989" },
  "famicom-zippy-race": { productId: "IF-01", publisher: "Irem", releaseDate: "07/18/1985" },
  "famicom-zoids-2-zenebasu-no-gyakushuu": { productId: "TFS-Z2", publisher: "Toshiba EMI", releaseDate: "01/27/1989" },
  "famicom-zoids-chuuou-tairiku-no-tatakai": { productId: "TFS-ZD", publisher: "Toemiland", releaseDate: "1987-05-09 00:00:00" },
  "famicom-zoids-mokushiroku": { productId: "TOM-ZF", publisher: "Tomy", releaseDate: "12/21/1990" },
  "famicom-zombie-hunter": { productId: "HSS-ZO, HSS-ZH", publisher: "Hi-Score Media Work", releaseDate: "1987-03-07 00:00:00" },
  "famicom-zunou-senkan-galg": { productId: "DBF-GA", publisher: "dB-Soft", releaseDate: "12/14/1985" },
  "famicom-1943": { productId: "CAP-43", publisher: "Capcom", releaseDate: "06/10/1988", alias: "1943: The Battle of Midway" },
  "famicom-abadox": { productId: "NAT-A3", publisher: "Natsume", releaseDate: "09/14/1989", alias: "Abadox: The Deadly Inner War" },
  "famicom-antarctic-adventure": { productId: "RC803", publisher: "Konami", releaseDate: "02/01/1984" },
  "famicom-chip-and-dale-rescue-rangers": { productId: "CAP-JD", publisher: "Capcom", releaseDate: "08/03/1990", alias: "Chip 'n Dale Rescue Rangers" },
  "famicom-chip-and-dale-rescue-rangers-2": { productId: "CAP-2D", publisher: "Capcom", releaseDate: "12/10/1993", alias: "Chip 'n Dale Rescue Rangers 2" },
  "famicom-double-dragon-ii": { productId: "TJC-W2", publisher: "Technos Japan", releaseDate: "12/22/1989", alias: "Double Dragon II: The Revenge" },
  "famicom-double-dragon-iii": { productId: "TJC-ZW", publisher: "Technos Japan", releaseDate: "09/14/1990", alias: "Double Dragon III: The Rosetta Stone" },
  "famicom-dragon-ball-z-gaiden": { productId: "BA-DBZ4", publisher: "Bandai", releaseDate: "08/06/1993", alias: "Dragon Ball Z Gaiden: Saiyajin Zetsumetsu Keikaku" },
  "famicom-dragon-ball-z-gekitou-tenkaichi-budoukai": { productId: "BA-DBZG", publisher: "Bandai", releaseDate: "12/25/1992" },
  "famicom-dragon-ball-z-ii": { productId: "BA-DBZ2", publisher: "Bandai", releaseDate: "08/10/1991", alias: "Dragon Ball Z II: Gekishin Freeza!!" },
  "famicom-dragon-ball-z-iii": { productId: "BA-DBZ3", publisher: "Bandai", releaseDate: "08/08/1992", alias: "Dragon Ball Z III: Ressen Jinzouningen" },
  "famicom-dragon-quest-ii": { productId: "EFC-D2", publisher: "Enix", releaseDate: "01/26/1987", alias: "Dragon Quest II: Akuryou no Kamigami" },
  "famicom-dragon-quest-iii": { productId: "EFC-D3", publisher: "Enix", releaseDate: "02/10/1988", alias: "Dragon Quest III: Soshite Densetsu he..." },
  "famicom-dragon-quest-iv": { productId: "EFC-D4", publisher: "Enix", releaseDate: "02/11/1990", alias: "Dragon Quest IV: Michibikareshi Monotachi" },
  "famicom-dragon-spirit": { productId: "NAM-DS", publisher: "Namco", releaseDate: "12/13/1988" },
  "famicom-duck-tales": { productId: "CAP-UK", publisher: "Capcom", releaseDate: "08/25/1989", alias: "DuckTales" },
  "famicom-goonies": { productId: "RC809", publisher: "Konami", releaseDate: "04/18/1986", alias: "Goonies, The" },
  "famicom-goonies-2": { productId: "RC818", publisher: "Konami", releaseDate: "08/06/1987", alias: "Goonies II: Fratelli Saigo no Chousen" },
  "famicom-gremlins-2": { productId: "SUN-GRM", publisher: "Sunsoft", releaseDate: "11/20/1990", alias: "Gremlins 2: The New Batch" },
  "famicom-hoshi-no-kirby": { productId: "HVC-KI", publisher: "Nintendo / HAL Laboratory", releaseDate: "03/23/1993", alias: "Kirby's Adventure" },
  "famicom-king-kong-2": { productId: "RC816", publisher: "Konami", releaseDate: "12/18/1986", alias: "King Kong 2: Yomigaeru Densetsu" },
  "famicom-kinnikuman": { productId: "BA-KIN", publisher: "Bandai", releaseDate: "11/21/1985", alias: "Kinnikuman: MUSCLE Tag Match" },
  "famicom-ninja-ryukenden-ii": { productId: "TCF-NW", publisher: "Tecmo", releaseDate: "04/06/1990", alias: "Ninja Gaiden II: The Dark Sword of Chaos" },
  "famicom-ninja-ryukenden-iii": { productId: "TCF-3N", publisher: "Tecmo", releaseDate: "06/14/1991", alias: "Ninja Gaiden III: The Ancient Ship of Doom" },
  "famicom-rockman-2": { productId: "CAP-XR", publisher: "Capcom", releaseDate: "12/24/1988", alias: "Mega Man 2" },
  "famicom-rockman-3": { productId: "CAP-XU", publisher: "Capcom", releaseDate: "09/28/1990", alias: "Mega Man 3" },
  "famicom-rockman-4": { productId: "CAP-4V", publisher: "Capcom", releaseDate: "12/06/1991", alias: "Mega Man 4" },
  "famicom-rockman-5": { productId: "CAP-5V", publisher: "Capcom", releaseDate: "12/04/1992", alias: "Mega Man 5" },
  "famicom-rockman-6": { productId: "CAP-6V", publisher: "Capcom", releaseDate: "11/05/1993", alias: "Mega Man 6" },
  "famicom-spelunker-ii": { productId: "IF-06", publisher: "Irem", releaseDate: "09/18/1987", alias: "Spelunker II: Yuusha e no Chousen" },
  "famicom-super-xevious": { productId: "NAM-SX", publisher: "Namco", releaseDate: "01/14/1986", alias: "Super Xevious: GAMP no Nazo" },
  "famicom-transformers-convoy-no-nazo": { productId: "TFC-TF", publisher: "Takara", releaseDate: "12/05/1986", alias: "Transformers: Mystery of Convoy" },
  "famicom-twinbee-3": { productId: "RC841", publisher: "Konami", releaseDate: "04/25/1989", alias: "TwinBee 3: Poko Poko Dai Maou" },
  "famicom-valkyrie-no-bouken": { productId: "NWB-3900", publisher: "Namco", releaseDate: "08/01/1986", alias: "Valkyrie no Bouken: Toki no Kagi Densetsu" },
  "famicom-wizardry": { productId: "HSP-09", publisher: "ASCII", releaseDate: "12/17/1987", alias: "Wizardry: Proving Grounds of the Mad Overlord" },
  "famicom-wizardry-knights-of-diamonds": { productId: "HSP-13", publisher: "ASCII", releaseDate: "06/30/1988", alias: "Wizardry II: The Knight of Diamonds" },
  "famicom-wizardry-legacy-of-the-llylgamyn": { productId: "HSP-32", publisher: "ASCII", releaseDate: "12/21/1990", alias: "Wizardry III: Legacy of Llylgamyn" },
  "famicom-zelda-no-densetsu-1": { productId: "FMC-ZEL", publisher: "Nintendo", releaseDate: "02/21/1986", alias: "The Legend of Zelda" },
  "famicom-akumajou-special": { productId: "RC844", publisher: "Konami", releaseDate: "09/14/1990", alias: "Boku Dracula-kun" },
  "famicom-altered-beast": { productId: "ASM-AB", publisher: "Asmik", releaseDate: "08/11/1989" },
  "famicom-moero-twinbee": { productId: "RC831", publisher: "Konami", releaseDate: "07/04/1986", alias: "Moero TwinBee: Cinnamon Hakase wo Sukue!" },
  "famicom-eggerland": { productId: "HAL-EG", publisher: "HAL Laboratory", releaseDate: "08/06/1987", alias: "Eggerland: Meikyuu no Fukkatsu" },
  "famicom-bikkuri-nekketsu-shinkiroku": { productId: "KAF-BN", publisher: "Technos Japan", releaseDate: "10/27/1990", alias: "Bikkuri Nekketsu Shinkiroku! Dokodemo Kin Medal" },
  "famicom-downtown-nekketsu-koushinkyoku": { productId: "KAF-DK", publisher: "Technos Japan", releaseDate: "03/14/1990", alias: "River City Ransom: Downtown Special" },
  "famicom-downtown-special": { productId: "KAF-DS", publisher: "Technos Japan", releaseDate: "04/26/1991", alias: "Downtown Special: Kunio-kun no Jidaigeki da yo Zenin Shuugo!" },
  "famicom-ike-ike-nekketsu-hockey-bu": { productId: "KAF-HB", publisher: "Technos Japan", releaseDate: "02/21/1992", alias: "Ike Ike! Nekketsu Hockey Bu: Subette Koronde Dairantou" },
  "famicom-nekketsu-koukou-dodgeball-bu-kunio-kun-soccer": { productId: "KAF-SO", publisher: "Technos Japan", releaseDate: "04/20/1990", alias: "Nekketsu Koukou Dodgeball-Bu: Soccer Hen" },
  "famicom-nekketsu-street-basket": { productId: "KAF-NS", publisher: "Technos Japan", releaseDate: "07/23/1993", alias: "Nekketsu Street Basket: Ganbare Dunk Heroes" },
  "famicom-dragon-buster-ii": { productId: "NAM-DB2", publisher: "Namco", releaseDate: "09/08/1987", alias: "Dragon Buster II: Yami no Fuuin" },
  "famicom-esper-dream-2": { productId: "RC842", publisher: "Konami", releaseDate: "06/30/1992", alias: "Esper Dream 2: Aratanaru Tatakai" },
  "famicom-ganbare-goemon-gaiden": { productId: "RC847", publisher: "Konami", releaseDate: "12/14/1990", alias: "Ganbare Goemon Gaiden: Kieta Ougon Kiseru" },
  "famicom-ganbare-goemon-gaiden-2": { productId: "RC858", publisher: "Konami", releaseDate: "09/27/1992", alias: "Ganbare Goemon Gaiden 2: Tenka no Zaihou" },
  "famicom-flipull": { productId: "TFC-FP", publisher: "Taito", releaseDate: "07/27/1990", alias: "Flipull: An Exciting Cube Game" },
  "famicom-rainbow-islands": { productId: "TFC-RI", publisher: "Taito", releaseDate: "02/08/1991", alias: "Rainbow Islands: The Story of Bubble Bobble 2" },
  "famicom-rod-land": { productId: "JF-30", publisher: "Jaleco", releaseDate: "10/25/1991" },
  "famicom-famicom-jump": { productId: "BA-FJ", publisher: "Bandai", releaseDate: "02/15/1989", alias: "Famicom Jump: Hero Retsuden" },
  "famicom-famicom-jump-ii": { productId: "BA-FJ2", publisher: "Bandai", releaseDate: "12/05/1991", alias: "Famicom Jump II: Saikyou no Shichinin" },
  "famicom-ninja-hattori-kun": { productId: "BA-NH", publisher: "Bandai", releaseDate: "03/05/1986" },
  "famicom-obake-no-q-tarou": { productId: "BA-OQ", publisher: "Bandai", releaseDate: "11/27/1985", alias: "Obake no Q-Tarou: Wanwan Panic" },
  "famicom-gegege-no-kitarou": { productId: "BA-GK", publisher: "Bandai", releaseDate: "09/27/1986", alias: "GeGeGe no Kitarou: Youkai Daimakyou" },
  "famicom-gegege-no-kitarou-2": { productId: "BA-GK2", publisher: "Bandai", releaseDate: "09/27/1987", alias: "GeGeGe no Kitarou 2: Youkai Gundan no Chousen" },
  "famicom-genpei-touma-den": { productId: "NAM-GT-4900", publisher: "Namco", releaseDate: "11/21/1986" },
  "famicom-herakles-no-eikou": { productId: "DFC-HE", publisher: "Data East", releaseDate: "07/13/1987", alias: "Herakles no Eikou: Toshin e no Michi" },
  "famicom-herakles-no-eikou-ii": { productId: "DFC-H2", publisher: "Data East", releaseDate: "12/22/1989", alias: "Herakles no Eikou II: Titan no Metsubou" },
  "famicom-higemaru-makaijima": { productId: "CAP-HM", publisher: "Capcom", releaseDate: "09/24/1987", alias: "Pirate Ship Higemaru" },
  "famicom-hokuto-no-ken-2": { productId: "TDF-H2", publisher: "Toei Animation", releaseDate: "08/12/1987", alias: "Hokuto no Ken 2: Seikimatsu Kyuuseishu Densetsu" },
  "famicom-hokuto-no-ken-3": { productId: "TDF-H3", publisher: "Toei Animation / Sega", releaseDate: "07/29/1988", alias: "Hokuto no Ken 3: Shin Seikimatsu Kyuuseishu Densetsu" },
  "famicom-hokuto-no-ken-4": { productId: "TDF-H4", publisher: "Toei Animation / Sega", releaseDate: "04/28/1989", alias: "Hokuto no Ken 4: Shichisei Hasha Gaiden" },
  "famicom-megami-tensei": { productId: "NAM-MT", publisher: "Namco", releaseDate: "09/11/1987", alias: "Digital Devil Story: Megami Tensei" },
  "famicom-megami-tensei-ii": { productId: "NAM-M2", publisher: "Namco", releaseDate: "01/07/1990", alias: "Digital Devil Story: Megami Tensei II" },
  "famicom-wai-wai-world-2": { productId: "RC852", publisher: "Konami", releaseDate: "01/03/1991", alias: "Wai Wai World 2: SOS!! Parsley Jou" },
  "famicom-rock-board": { productId: "RC857", publisher: "Konami", releaseDate: "03/06/1993", alias: "Rock Board: That's Paradise" },
  "famicom-tiny-toon-adventures-2": { productId: "RC861", publisher: "Konami", releaseDate: "07/22/1993", alias: "Tiny Toon Adventures 2: Montana Land e Youkoso" },
  "famicom-splatterhouse": { productId: "NAM-SP-5800", publisher: "Namco", releaseDate: "12/14/1990" },
  "famicom-magical-taruruuto-kun": { productId: "BA-MT", publisher: "Bandai", releaseDate: "12/21/1990" },
  "famicom-magical-taruruuto-kun-2": { productId: "BA-MT2", publisher: "Bandai", releaseDate: "12/20/1991" },
  "famicom-kamen-rider-club": { productId: "BA-KR", publisher: "Bandai", releaseDate: "07/28/1988" },
  "famicom-kamen-rider-sd": { productId: "BA-KSD", publisher: "Bandai", releaseDate: "12/18/1992" },
  "famicom-yu-yu-hakusho": { productId: "BAN-YY", publisher: "Bandai", releaseDate: "12/25/1993" },
  "famicom-dr-jekyll-and-mr-hyde": { productId: "TFC-JH", publisher: "Toho", releaseDate: "04/08/1988" },
  "famicom-golgo-13-dai-1-shou": { productId: "VIC-G1", publisher: "Vic Tokai", releaseDate: "07/29/1988", alias: "Golgo 13: Dai-1-Shou - Kamigami no Tasogare" },
  "famicom-golgo-13-dai-2-shou": { productId: "VIC-G2", publisher: "Vic Tokai", releaseDate: "08/09/1990", alias: "Golgo 13: Dai-2-Shou - Icarus no Nazo" },
  "famicom-deja-vu": { productId: "KSC-DJ", publisher: "Kemco / Icom Simulations", releaseDate: "09/29/1989" },
  "famicom-murder-on-the-mississippi": { productId: "PNF-MS", publisher: "Pony Canyon", releaseDate: "1987-02-03 00:00:00" },
  "famicom-tenchi-wo-kurau": { productId: "CAP-TC", publisher: "Capcom", releaseDate: "07/26/1989", alias: "Destiny of an Emperor" },
  "famicom-tenchi-wo-kurau-ii": { productId: "CAP-T2", publisher: "Capcom", releaseDate: "01/30/1991", alias: "Tenchi wo Kurau II: Sekiheki no Tatakai" },
  "famicom-ys-ii": { productId: "VFR-Y3", publisher: "Victor Musical Industries", releaseDate: "12/22/1989", alias: "Ys II: Ancient Ys Vanished - The Final Chapter" },
  "famicom-ys-iii": { productId: "VFR-Y4", publisher: "Victor Musical Industries", releaseDate: "07/05/1991", alias: "Ys III: Wanderers from Ys" },
  "famicom-lupin-the-3rd-pandora-no-isan": { productId: "NAM-LP", publisher: "Namco", releaseDate: "09/04/1987", alias: "Lupin III: Pandora no Isan" },
  "famicom-meta-fight": { productId: "SUN-MF", publisher: "Sunsoft", releaseDate: "06/17/1988", alias: "Blaster Master" },
  "famicom-metal-storm": { productId: "IF-14", publisher: "Irem", releaseDate: "03/15/1991", alias: "Metal Storm" },
  "famicom-baseball-star": { productId: "SFX-BS", publisher: "SNK", releaseDate: "11/12/1988", alias: "Baseball Star: Mezase Sankanou!!" },
  "famicom-itadaki-street": { productId: "EFC-IS", publisher: "Enix", releaseDate: "09/26/1991" },
  "famicom-sansara-naga": { productId: "VIC-SN", publisher: "Vic Tokai", releaseDate: "12/08/1990" },
  "famicom-tom-sawyer": { productId: "KKS-YB", publisher: "Seta", releaseDate: "1989-06-02 00:00:00", alias: "Tom Sawyer no Bouken" },
}
